import { WEBAPP_BUILD_NUMBER, WEBAPP_VERSION } from "@/lib/app-version";

// Build 418 release-contract: owner-only continuity monitor on top of Build 417 explicit zone opt-in.

export type ReleaseConfidence = "confirmed" | "reconstructed";

export type ReleaseHistoryEntry = {
  id: string;
  version: string;
  build: string | null;
  releasedAt: string;
  title: string;
  newItems: string[];
  problems: string[];
  causes: string[];
  fixes: string[];
  now: string[];
  before?: string;
  after?: string;
  technicalDetails?: string[];
  confidence: ReleaseConfidence;
};

export const CURRENT_RELEASE: ReleaseHistoryEntry = {
  id: `v${WEBAPP_VERSION}-build-${WEBAPP_BUILD_NUMBER}-release-history`,
  version: WEBAPP_VERSION,
  build: WEBAPP_BUILD_NUMBER,
  releasedAt: "2026-09-24",
  title: "BETA · App continuïteitsbewaker + Bybit betaalreserve",
  newItems: [
    "Nieuwe owner-only kaart App kosten & betalingen op HOME met live status van ChatGPT, GitHub, Google Cloud en Bybit betaalreserve.",
    "Nieuwe mobiele continuïteitspagina met bekende betalingen, bekende maandkosten, providerstatus, veiligheidsbuffer en afhankelijkheden.",
    "Bybit krijgt een volledig aparte read-only Funding-walletkoppeling; de backend accepteert uitsluitend een sleutel waarvoor Bybit readOnly=1 bevestigt.",
    "Kritieke continuiteitsmeldingen kunnen bij appstart verschijnen en worden bewust bevestigd zonder trading state te wijzigen.",
  ],
  problems: [
    "Een gemiste betaling of uitgezette billing kon de app onverwacht raken zonder één centraal overzicht.",
    "Kosten, providerstatus en betaalreserve moesten verspreid over leveranciers handmatig worden onthouden.",
  ],
  causes: [
    "Er bestond nog geen gescheiden read-only continuiteitsdomein naast de trading runtime.",
    "Providerdata had nog geen uniform onderscheid tussen live, handmatig, berekend en onbekend.",
  ],
  fixes: [
    "Continuity Dashboard is hard owner-only op een immutable UID-claim en andere accounts starten geen continuity-providercalls.",
    "Een dedicated Secret Manager secret bewaart uitsluitend de aparte read-only Bybit continuïteitssleutel.",
    "Google Cloud billing wordt fail-closed gecontroleerd: uitgeschakelde billing is KRITIEK en ontbrekend leesrecht blijft zichtbaar als niet geverifieerd.",
    "ChatGPT-consumentenbilling blijft handmatig zolang geen ondersteunde live billinginterface beschikbaar is; onbekende bedragen en vervaldatums worden niet verzonnen.",
  ],
  now: [
    "HOME toont de continuïteitskaart alleen aan het BETA-owneraccount.",
    "Bybit kan vanuit de app worden getest en gekoppeld; het API-secret komt na opslag niet terug in browserresponses.",
    "Providerkaarten tonen hun databron en afhankelijkheid, zodat groen alleen uit bevestigde controles komt.",
    "De module bevat geen order-, DCA-, TP/SL-, zone-, soldier-, scanner-, leverage- of Close All-mutatiepad.",
  ],
  before: "Build 417 maakte Portfolio Koers informatief by default en vereiste expliciete owner opt-in voor de Zone-Soldatenstrategie.",
  after: "Build 418 voegt daar een volledig losstaande owner-only continuïteitslaag aan toe voor providerstatus, betalingen en read-only betaalreserve.",
  technicalDetails: [
    "Webroutes: /api/continuity, /refresh, /bybit/test, /bybit, /settings en /alerts/ack.",
    "Cloudroutes gebruiken dezelfde Firebase sessie en daarboven een aparte continuity owner-UID gate.",
    "Bybit V5 wordt uitsluitend gelezen via query-api en Funding balance endpoints; er bestaat geen muterende Bybit methode in de continuity client.",
    "Providerwaarden gebruiken LIVE_API, MANUAL, CALCULATED of UNKNOWN en onbekende due dates worden niet hardcoded.",
  ],
  confidence: "confirmed",
};

const HISTORICAL_RELEASES: ReleaseHistoryEntry[] = [
  {
  id: "v46-build-417-explicit-zone-opt-in",
  version: "46",
  build: "417",
  releasedAt: "2026-09-24",
  title: "BETA · Portfolio Koers informatief + expliciete Zone-Soldatenstrategie",
  newItems: [
    "Portfolio Koers en de 15m-zones zijn nu informatief beschikbaar zonder dat ze slots, orders of position sizing wijzigen.",
    "Zone-Soldatenstrategie heeft een expliciete AAN/UIT-keuze in Botconfigurator V2 en is standaard UIT, ook voor de BETA-owner.",
    "Een opt-in-marker voorkomt dat oude Build-416 state of alleen BETA-toegang als toestemming voor zone-trading telt.",
    "ASTER, Botconfigurator en Portfolio Koers tonen duidelijk TRADITIONEEL, ZONE SOLDATEN of ZONE DRAINING.",
    "Uitschakelen met open zone-posities gaat veilig naar ZONE_DRAINING: geen nieuwe zone-soldaten, bestaande TP/DCA/SL-management blijft intact.",
  ],
  problems: [
    "Build 416 koppelde feature-beschikbaarheid nog impliciet aan zoneSoldiersEnabled=true.",
    "Portfolio Koers bevatte nog een legacy pad dat globale LONG/SHORT-slots kon aanpassen.",
    "De actieve handelsstrategie was niet op ieder relevant scherm onmiddellijk zichtbaar.",
  ],
  causes: [
    "Availability, user consent en runtime lifecycle waren nog niet als drie afzonderlijke states gemodelleerd.",
    "De oude zone-advisor UI stamde van vóór de zone-owned strategie en had nog een settings-writepad.",
  ],
  fixes: [
    "BETA/owner bepaalt alleen beschikbaarheid; zoneSoldiersEnabled vereist zoneSoldiersOptInVersion >= 1 en een expliciet opgeslagen gebruikerskeuze.",
    "STABLE of niet-geautoriseerde accounts worden server-side altijd naar zoneSoldiersEnabled=false gedwongen.",
    "Portfolio Koers bevat geen PUT/order/slotmutatiepad meer en toont traditionele modus expliciet als INFORMATIEF.",
    "Zone sizing en exposure-balancer worden alleen opgebouwd wanneer de server-authoritatieve zone_mode waar is.",
    "Open zone-owned posities blijven bij uitschakelen beheerd via DRAINING totdat ze flat zijn.",
  ],
  now: [
    "Traditionele strategie: Portfolio Koers toont zone, afstand en niveaus maar stuurt geen trades.",
    "Zone-Soldatenstrategie: pas na expliciet AAN + Opslaan gebruikt de runtime de bevestigde 15m-zone voor nieuwe zone-owned entries.",
    "Deploy, login, bootstrap of restart kan een uitgeschakelde zone-strategie niet automatisch inschakelen.",
  ],
  before: "Build 416 maakte zone trading owner-only, maar BETA-beschikbaarheid kon nog impliciet als activatie werken.",
  after: "Build 417 scheidt informatie, beschikbaarheid en trading-consent volledig en maakt de actieve strategie overal zichtbaar.",
  technicalDetails: [
    "zoneSoldiersOptInVersion=1 is vereist naast zoneSoldiersEnabled=true.",
    "zoneSoldierLifecycle is ACTIVE, DRAINING of OFF.",
    "Portfolio Koers heeft geen Strategy-2 settings-writepad meer.",
    "Owner-only availability blijft behouden; STABLE krijgt geen zone-tradinggedrag.",
    "Web- en backendcontracten bewaken expliciet dat Portfolio Koers geen Strategy-2 settings kan muteren.",
  ],
  confidence: "confirmed",
},
  {
    id: "v46-build-416-owner-only-zone-sizing",
    version: "46",
    build: "416",
    releasedAt: "2026-09-24",
    title: "BETA · owner-only zonesoldaten + rustige inzetgroei",
    newItems: ["Owner-only zone-owned soldaten, persistente zoneherkomst, exposure-balancer en rustige lineaire inzetgroei per zoneafstand."],
    problems: ["Feature-beschikbaarheid en expliciete gebruikersactivatie waren nog niet volledig gescheiden."],
    causes: ["Build 416 gebruikte de BETA-releasegate nog om ontbrekende zoneSoldiersEnabled-state impliciet aan te vullen."],
    fixes: ["Owner-only runtimebeveiliging en monotone zone sizing werden toegevoegd; Build 417 maakt de opt-in daarna expliciet."],
    now: ["Historische basis voor de expliciete strategie-keuze van Build 417."],
    confidence: "confirmed",
  },

  {
    id: "v46-build-414-aster-cold-start-formation-dashboard",
    version: "46",
    build: "414",
    releasedAt: "2026-09-24",
    title: "ASTER cold start · zonefocus · Formation Dashboard",
    newItems: [
      "De PWA en root-start openen direct op ASTER met Portfolio Koers bovenaan; HOME blijft via de onderste navigatie bereikbaar.",
      "Portfolio Koers gebruikt een compactere zone-aware openingswindow zodat de actuele equity en aangrenzende zones centraal leesbaar zijn.",
      "Koersinstructie is omgebouwd tot Formation Dashboard met actieve soldaten, LONG/SHORT-verdeling, stoelcapaciteit, vrije stoelen, doelcapaciteit en verschil/actie.",
      "Procentuele zonebadges zijn groter gemaakt en de absolute prijsas is visueel teruggenomen.",
    ],
    problems: [
      "Een volledig afgesloten app kon opnieuw op de algemene HOME/Overboeken-landingspagina starten.",
      "Build 413 kon op 15m nog voldoende oude candles in de openingswindow houden om de actuele equity bovenin de grafiek samen te drukken.",
      "De oude koersinstructie vermengde huidige stoelcapaciteit met actieve posities en maakte vrije capaciteit niet expliciet zichtbaar.",
    ],
    causes: [
      "HomeNavigationBridge synthetiseerde bij een root-start expliciet tmView=home en de hoofdpage initialiseerde vóór routing nog op Hyperliquid.",
      "De minimale zone-focuswindow van Build 413 was nog te groot voor een tijdreeks met een recente sprong of historiegat.",
      "De instructiekaart was ontstaan als actie-uitleg en niet als operationeel overzicht van actief, capaciteit, vrij en doel.",
    ],
    fixes: [
      "Manifest start_url wijst naar #/aster; de runtime root-fallback zet eveneens ASTER en de eerste React-state is ASTER zodat er geen HOME-flash nodig is.",
      "De focuswindow is per timeframe verder verkleind en mag na zes recente relevante candles al stoppen vóór een oude candle ver buiten de actieve zone.",
      "De kaart onderscheidt actieve LONG/SHORT-posities, ingestelde capaciteit, vrije stoelen en gewenste zonecapaciteit expliciet.",
      "De bestaande actieknop blijft uitsluitend longSlots, shortSlots en maximumPositions opslaan; er is geen directe exchange-order toegevoegd.",
    ],
    now: [
      "Cold start → ASTER → Portfolio Koers → Portfolio Snapshot.",
      "De actuele koers staat bij openen dichter bij het midden van het relevante zonegebied en handmatig uitzoomen blijft mogelijk omdat geen historische candle wordt verwijderd.",
      "De gebruiker leest in één kaart: zone/bias, actief totaal, LONG/SHORT actief, capaciteit, vrij, doel, verschil, zoneafstanden en de bestaande seat-capacity actie.",
    ],
    before: "Build 413 maakte de zoneafstanden percentage-first, maar startte nog niet direct op ASTER en de openingsfocus kon bij recente grote historieverschillen nog te ruim zijn.",
    after: "Build 414 maakt ASTER de operationele cold-start, verkleint de initiële chartcamera verder en maakt de koersinstructie een Formation Dashboard.",
    technicalDetails: [
      "Geen candle-, zone-, Bollinger-, DCA-, TP/SL-, entry- of orderlogica gewijzigd.",
      "Alle volledige historische candles blijven in de dataset en worden zichtbaar bij handmatig uitzoomen.",
      "Actief = multiBb.activeLong/activeShort; capaciteit = settings.longSlots/shortSlots; vrij = max(0, capaciteit - actief); doel = zone-advisor desiredLongSlots/desiredShortSlots.",
      "De zone-focus regressietest gebruikt recente candles binnen het relevante zonevenster en bevestigt dat een oudere, verre candle buiten de initiële camera kan blijven.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-413-portfolio-koers-percent-focus",
    version: "46",
    build: "413",
    releasedAt: "2026-09-24",
    title: "Portfolio Koers · zonefocus en procentuele afstanden",
    newItems: [
      "Portfolio Koers opent automatisch dichter op de actuele equity en de aangrenzende zonegrenzen, in plaats van een groot historisch prijsbereik samen te persen.",
      "De eerstvolgende grens omhoog en omlaag worden primair als procentuele afstand tot de actuele portfolio-equity getoond.",
      "De koersinstructie toont daarnaast compact hoeveel procent van de actieve zone al is doorlopen richting de bovengrens.",
    ],
    problems: [
      "De standaardweergave kon oude, ver verwijderde candles meenemen waardoor de actuele zone op mobiel als een dunne strook bovenin verscheen.",
      "Beide aangrenzende grenzen heetten VOLGENDE en toonden vooral absolute bedragen, waardoor een lagere grens als een tweede volgende zone kon worden gelezen.",
    ],
    causes: [
      "De initiële viewport gebruikte per timeframe een relatief groot vast aantal candles en liet de prijs-as volledig door die historische range bepalen.",
      "De grenslabels waren oorspronkelijk ontworpen als exacte triggerprijzen en maakten de richting omhoog/omlaag semantisch onvoldoende expliciet.",
    ],
    fixes: [
      "Per timeframe is de maximale openingswindow verkleind en een zone-aware focusfunctie stopt vóór oude candles die ver buiten het actuele zonegebied liggen.",
      "Transparante autoscale-ankers houden de actuele lower/upper zonegrens met beperkte padding in beeld zonder koersdata te wijzigen of te verzinnen.",
      "Grenslabels tonen nu richting, doelzone en live procentuele afstand; exacte prijzen blijven alleen secundair als detail/title beschikbaar.",
      "De koersinstructie gebruikt dezelfde live percentages en toont een 0–100% zoneprogressie. Zone-, soldaten-, DCA-, TP- en orderlogica zijn niet gewijzigd.",
    ],
    now: [
      "Bij 144,85 met Z0 op 145,27 en Z-2 op 143,21 leest de gebruiker ongeveer ↑ Z0 · +0,29% en ↓ Z-2 · −1,13%.",
      "De gebruiker ziet direct de huidige zone, de afstand omhoog en omlaag, de positie binnen de zone en de bestaande LONG/SHORT-soldatenactie.",
      "Timeframewissels naar 1m, 5m, 15m, 1u, 4u en 24u krijgen dezelfde zonegerichte openingslogica.",
    ],
    before: "Build 412 verwijderde de oude 100-stoelengrens, maar de Portfolio Koers kon nog te ver uitgezoomd openen en absolute grensprijzen dominant tonen.",
    after: "Build 413 maakt de Portfolio Koers percentage-first en opent automatisch op het relevante zonegebied, zonder tradinglogica te veranderen.",
    technicalDetails: [
      "afstand % = ((grens - actuele equity) / actuele equity) × 100.",
      "zoneProgress = clamp(((equity - lowerBoundary) / (upperBoundary - lowerBoundary)) × 100, 0, 100).",
      "Geen ontbrekende historische koerswaarden worden aangevuld of geïnterpoleerd.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-412-portfolio-koers-capacity",
    version: "46",
    build: "412",
    releasedAt: "2026-09-24",
    title: "Portfolio Koers · oude 100-stoelengrens verwijderd",
    newItems: [
      "De BETA koersinstructie kan LONG + SHORT nu boven de oude grens van 100 stoelen brengen, met een platformveiligheidsgrens van 400.",
      "De exacte 70L / 30S situatie met 28 actieve SHORT-posities is als regressietest vastgelegd: Zone +2 vraagt dan 8 extra SHORT-stoelen en kan naar 70L / 38S.",
      "Een browser/netwerkfout wordt niet meer als rauwe tekst Failed to fetch getoond, maar als een duidelijke melding dat niets is gewijzigd.",
    ],
    problems: [
      "Bij 70L / 30S en Zone +2 berekende de app correct dat 8 extra SHORT-soldaten nodig waren, maar blokkeerde dezelfde actie vervolgens met LIMIET 100.",
      "De limiet was niet gekoppeld aan beschikbaar saldo of de actuele Multi-BB marktcapaciteit en was daardoor een kunstmatige blokkade.",
      "Na een tijdelijke netwerkfout kon de technische browsermelding Failed to fetch onder de koersinstructie blijven staan.",
    ],
    causes: [
      "Een oude 100-stoelengrens stond dubbel in de zone-advisor, de Strategy-2 webguard, de configurator en de legacy backendcompatibiliteit.",
      "De koersinstructie gaf een onbewerkte fetch-exception direct door aan de UI.",
    ],
    fixes: [
      "De gedeelde webguards, zone-advisor en legacy Strategy-2 compatibiliteitsvalidatie zijn op de bestaande 400-stoelen platformgrens uitgelijnd.",
      "De soldatenknop gebruikt dezelfde gedeelde platformgrens en schrijft bij 70L / 38S maximumPositions=108 in plaats van de actie op 100 te blokkeren.",
      "Werkelijke nieuwe entries blijven afhankelijk van live beschikbare margin, marktcapaciteit, instapfilters en runtime-risicocontroles; de knop verhoogt alleen stoelcapaciteit.",
      "Netwerkfouten blijven fail-closed: bij een mislukte fetch of save wordt geen stoelverdeling gewijzigd.",
    ],
    now: [
      "De oude 100-grens kan een geldige +8 SHORT-instructie niet meer tegenhouden.",
      "Als de live situatie bij opslaan nog steeds 70L / 30S met 28 actieve SHORT-posities en Zone +2 is, wordt de doelcapaciteit 70L / 38S.",
      "Een echte veiligheids- of backendvalidatie blijft zichtbaar als concrete reden in plaats van een tegenstrijdige 100-limiet.",
    ],
    before: "Build 411 maakte de tijdlijn veilig en fail-closed, maar erfde nog de oude 100-stoelengrens uit eerdere configuratiecode.",
    after: "Build 412 scheidt geld/entry-risico van stoelcapaciteit en verwijdert de kunstmatige 100-blokkade uit de BETA koersinstructie.",
    technicalDetails: [
      "PORTFOLIO_ZONE_MAX_TOTAL_SLOTS = 400.",
      "Web settings guard: maximumPositions, LONG en SHORT worden maximaal op 400 begrensd.",
      "Legacy Strategy2Config accepteert maximumPairs tot 400; Multi BB houdt daarnaast zijn eigen universe-/marktcapaciteitsvalidatie.",
      "De knop opent geen market order direct; hij past longSlots, shortSlots en maximumPositions aan.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-411-portfolio-koers-continuity",
    version: "46",
    build: "411",
    releasedAt: "2026-09-24",
    title: "Portfolio Koers · tijdlijncontinuïteit en veilige soldatensturing",
    newItems: [
      "Live candle follow, expliciete historiegaten en fail-closed soldatensturing bij onvolledige 15m historie.",
      "Server-side equitysampling bouwt de Portfolio Koers ook zonder open browsertab verder op.",
    ],
    problems: ["De chart kon na uren zonder webapp een tijdsgat tonen en de viewport kon op een oude candle blijven staan."],
    causes: ["Portfolio-equity werd voorheen onvoldoende continu server-side vastgelegd en zoneberekening maakte nog geen expliciet onderscheid tussen aaneengesloten en onderbroken tijdreeksen."],
    fixes: ["Nieuwe candles volgen realtime, ontbrekende waarden worden niet verzonnen en de zone-advisor wacht op voldoende aaneengesloten bevestigde candles."],
    now: ["Build 412 behoudt deze continuïteitsbeveiliging en corrigeert daarna de oude 100-stoelengrens."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-410-zone-basis-exposure",
    version: "46",
    build: "410",
    releasedAt: "2026-09-24",
    title: "Portfolio Koers · zonebasis en netto exposure verduidelijkt",
    newItems: [
      "De koersinstructie toont expliciet dat de zone uit portfolio-equity en de canonieke 15m support/resistance-ladder komt.",
      "De actuele equity en de onder-/bovengrens van de actieve zone worden direct in de instructiebalk uitgelegd.",
      "NETTO OPEN is hernoemd naar NETTO EXPOSURE en wordt niet meer met een misleidend minteken als verliesbedrag getoond.",
    ],
    problems: [
      "Een bedrag zoals -US$ 492 SHORT kon logisch worden gelezen als een verlies van 492 dollar, terwijl het netto directionele exposure was.",
      "Daardoor leek een zone zoals Z-1 onmogelijk of fout, omdat de kaart niet uitlegde welke grootheid de zone werkelijk bepaalt.",
    ],
    causes: [
      "De exposure-tegel gebruikte signed money-formatting terwijl SHORT al apart als richting werd getoond.",
      "De koersinstructie toonde zone, gewenste stoelen en volgende grenzen, maar niet de bron van de zoneberekening.",
    ],
    fixes: [
      "Netto exposure wordt als absolute exposurewaarde met LONG/SHORT-richting getoond, niet als winst/verlies.",
      "De koersinstructie vermeldt portfolio-equity, 15m support/resistance, de actuele equity en de band van de actieve zone.",
      "Geen zone-, order-, DCA-, TP- of stoelberekening gewijzigd; alleen semantiek en uitleg zijn aangescherpt.",
    ],
    now: [
      "Een gebruiker kan direct zien waarom de app bijvoorbeeld Z-1 toont en welke equitygrenzen daarbij horen.",
      "Een SHORT netto exposure van US$ 492 kan niet meer worden verward met -US$ 492 PnL.",
      "Build 411 voegt hierna tijdlijncontinuïteit en fail-closed soldatensturing toe.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-409-zone-colors",
    version: "46",
    build: "409",
    releasedAt: "2026-09-23",
    title: "Portfolio Koers · duidelijke afzonderlijke zonekleuren",
    newItems: ["Lagere zones kregen duidelijk verschillende forest/teal/emerald fills; Zone 0 blauw en hogere zones amber/oranje/rood."],
    problems: ["Lagere zones en hun grenzen leken op mobiel nog te veel op één groen vlak."],
    causes: ["Kleurverschillen zaten te veel in opacity en te weinig in hue."],
    fixes: ["Signed zonefills verder uit elkaar gezet en gewone boundaries neutraal gemaakt."],
    now: ["Build 410 verandert hierna alleen de uitleg van zonebasis en exposure; de Build-409 kleurhiërarchie blijft behouden."],
    confidence: "confirmed",
  },

  {
    id: "v46-build-408-beta-zone-decision-map",
    version: "46",
    build: "408",
    releasedAt: "2026-09-23",
    title: "Portfolio Koers · BETA zonekaart wordt beslissingskaart",
    newItems: [
      "Aparte structural boundary-layer, actieve-zone-highlight en exacte volgende omhoog/omlaag trigger.",
      "Koersinstructie toont reden, huidige/gewenste formatie en volgende levels.",
    ],
    problems: ["Lagere zones bleken op OLED-schermen ondanks aparte classes visueel nog te veel op één groen vlak te lijken."],
    causes: ["De signed negatieve zonefills verschilden vooral in opacity en te weinig in hue."],
    fixes: ["Build 409 vergroot uitsluitend het kleurverschil en neutraliseert gewone grenslijnen."],
    now: ["De decision-maplogica en functionele soldatenknop blijven ongewijzigd."],
    confidence: "confirmed",
  },

  {
    id: "v46-build-407-canonical-beta-zones",
    version: "46",
    build: "407",
    releasedAt: "2026-09-23",
    title: "Portfolio Koers · één canonieke BETA-zonekaart op alle timeframes",
    newItems: [
      "Alle BETA-timeframes gebruiken dezelfde canonieke 15m-zonebron voor prijszones en koersinstructie.",
      "4u en 24u vallen niet meer terug naar ZONE — wanneer hun eigen timeframe te weinig bevestigde swingzones heeft.",
    ],
    problems: ["Build 406 kon op 4u nog een lege zonebron krijgen terwijl 15m voldoende zone-informatie had."],
    causes: ["De BETA-ladder werd nog per geselecteerd chart-timeframe gevoed."],
    fixes: ["15m Portfolio Koers zones zijn de canonieke BETA-zonebron; candles/Bollinger/markers blijven timeframe-specifiek."],
    now: ["Build 408 verfijnt uitsluitend de leesbaarheid, grenshiërarchie en beslisinformatie van deze canonieke zonekaart."],
    confidence: "confirmed",
  },

  {
    id: "v46-build-406-portfolio-koers-full-beta-zones",
    version: "46",
    build: "406",
    releasedAt: "2026-09-23",
    title: "Portfolio Koers · volledige BETA prijszones en juiste zone-instructie",
    newItems: [
      "BETA-prijszones vullen de volledige zichtbare grafiekhoogte.",
      "Zones worden veilig doorgetrokken tot -3 en +3 wanneer de koers buiten bevestigde banden komt.",
    ],
    problems: ["Build 405 kon buiten bevestigde banden nog op de dichtstbijzijnde bekende zone blijven hangen."],
    causes: ["De actieve zone en buitenste overlaygrenzen gebruikten nog alleen de bevestigde banden van het geselecteerde timeframe."],
    fixes: ["Volledige ladder, halfweggrenzen en full-height outer zones toegevoegd."],
    now: ["Build 407 maakt diezelfde ladder timeframe-onafhankelijk voor het BETA-account."],
    confidence: "confirmed",
  },

  {
    id: "v46-build-405-portfolio-koers-beta-zone-advisor",
    version: "46",
    build: "405",
    releasedAt: "2026-09-23",
    title: "Portfolio Koers · BETA zone-instructie met werkende soldatenknop",
    newItems: [
      "Prijszones zijn voor het BETA-owner account duidelijker en contrastrijker gemaakt op basis van de goedgekeurde referentie.",
      "Onder de grafiek staat een koersinstructiebalk die de actieve zone vertaalt naar benodigde vrije LONG- of SHORT-stoelen.",
      "De soldatenknop past de echte server-side LONG/SHORT-stoelcapaciteit aan en bevestigt de nieuwe verdeling.",
    ],
    problems: [
      "De bestaande zonekleuren waren op 1m, 15m en vooral 4u te subtiel om de actieve prijszone direct te herkennen.",
      "De grafiek gaf nog geen concrete instructie wanneer een zone extra vrije capaciteit vroeg of wanneer ongebruikte zonecapaciteit terug kon.",
    ],
    causes: [
      "Build 401 hield de zone-overlay bewust rustig en had nog geen koppeling tussen de actuele zone, live stoelbezetting en de bestaande Strategy-2 settings-endpoint.",
    ],
    fixes: [
      "Alleen voor het server-bevestigde BETA-owner account worden sterkere rood/amber/blauw/groene zonefills en duidelijke grenslijnen gebruikt; zonetekst in de chart blijft verborgen.",
      "Iedere stap buiten Zone 0 reserveert vijf vrije soldaten aan de richting die bij die zone hoort: hogere zones SHORT, lagere zones LONG, maximaal vijftien.",
      "Voor iedere knopdruk worden de actuele settings en live bezetting opnieuw opgehaald; daarna worden uitsluitend longSlots, shortSlots en maximumPositions opgeslagen.",
      "Naar-huis-acties kunnen nooit onder het aantal actieve posities reduceren en de bestaande limiet van 100 totale stoelen blijft hard.",
    ],
    now: [
      "Voorbeeld uit de referentie: bij Zone +2, 60L/30S capaciteit en 60L/30S actief verschijnt Stuur 10 extra SHORT-soldaten; de knop zet de capaciteit server-side op 60L/40S.",
      "De knop opent of sluit geen exchange-positie rechtstreeks: hij wijzigt de echte stoelcapaciteit, waarna de bestaande instapvoorwaarden bepalen of vrije stoelen gevuld worden.",
    ],
    before: "Build 404 maakte de stoelbezetting in Botconfigurator V2 semantisch gelijk aan de live LONG/SHORT-bezetting.",
    after: "Build 406 corrigeert de buitenste zonegeometrie en actieve-zonebepaling.",
    technicalDetails: [
      "Account-gate: /api/releases/me moet channel=BETA en bot_configurator_v2.enabled=true teruggeven.",
      "Actie-endpoint: PUT /api/exchanges/aster/strategy2/settings.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-404-botconfigurator-live-seat-occupancy",
    version: "46",
    build: "404",
    releasedAt: "2026-09-23",
    title: "Botconfigurator V2 · live stoelbezetting per zijde",
    newItems: [
      "Stap 2 toont nu per zijde actieve posities tegenover de ingestelde stoelcapaciteit.",
      "De LONG- en SHORT-balken zijn echte bezettingsmeters; totaal toont eveneens bezet/capaciteit.",
    ],
    problems: [
      "De vorige LONG/SHORT-balken toonden het aandeel van iedere zijde in het ingestelde totaal, waardoor 30/30 SHORT visueel maar voor een derde gevuld leek.",
      "Dat suggereerde ten onrechte dat er nog SHORT-stoelen vrij waren terwijl de SHORT-cap al volledig bezet was.",
    ],
    causes: ["De balkbreedte werd berekend als sideSlots / totalSlots in plaats van activeSide / sideSlots."],
    fixes: [
      "Live activeLong en activeShort uit het bestaande Multi-BB rapport sturen nu de bezettingsbalken.",
      "Balkbreedte wordt per zijde begrensd op actieve posities gedeeld door de ingestelde capaciteit.",
      "Tekst toont expliciet bezet/capaciteit, bijvoorbeeld 50/60 LONG, 30/30 SHORT en 80/90 totaal.",
    ],
    now: [
      "Bij 50 actieve LONG op 60 stoelen staat LONG op 83,3%; bij 30 actieve SHORT op 30 stoelen staat SHORT volledig vol.",
      "Vrije capaciteit opent geen posities vanzelf; de bestaande instapvoorwaarden blijven leidend.",
      "De wijziging is uitsluitend presentatie in de BETA Botconfigurator; trading-, DCA-, TP- en slotlimietlogica is niet aangepast.",
    ],
    before: "Build 403 introduceerde de geïsoleerde BETA Botconfigurator V2.",
    after: "Build 404 maakt de stoelvisualisatie semantisch gelijk aan de werkelijke live bezetting.",
    technicalDetails: [
      "Bron voor bezetting: strategy2.multiBb/multiBbReport activeLong en activeShort.",
      "Capaciteit blijft afkomstig uit de actuele V2 draft longSlots en shortSlots, zodat een wijziging direct 50/60 of 30/30 kan tonen vóór een nieuwe entry.",
      "Bij ontbrekende live telling wordt —/capaciteit getoond in plaats van een verzonnen bezettingswaarde.",
      "Regressietest bewaakt dat sideSlots/totalSlots niet opnieuw als bezettingsformule wordt gebruikt.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-403-botconfigurator-v2-beta-ui",
    version: "46",
    build: "403",
    releasedAt: "2026-09-23",
    title: "Botconfigurator V2 · BETA UI en geïsoleerde blokrelease",
    newItems: ["Nieuwe één-pagina Botconfigurator V2 met acht stappen, BETA-owner functies en Releasecentrum."],
    problems: ["De oude instellingenpagina was functioneel maar organisch gegroeid en nieuwe functies moesten geïsoleerd getest kunnen worden."],
    causes: ["UI-volgorde volgde historische featurebouw en er was nog geen blokgewijze BETA/STABLE bediening in de nieuwe configurator."],
    fixes: ["V2 werd lazy geladen achter server-side release-entitlements; STABLE bleef op de bestaande legacy configurator."],
    now: ["Build 404 verfijnt uitsluitend de stoelbezettingsweergave van deze BETA-configurator."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-402-botconfigurator-beta-backend",
    version: "46",
    build: "402",
    releasedAt: "2026-09-23",
    title: "Botconfigurator V2 BETA-releasefundering",
    newItems: ["Server-side BETA/STABLE releasekanalen, directional Bollinger en exposure-refill configuratiecontract."],
    problems: ["Nieuwe functies moesten per account functioneel testbaar worden zonder stable gebruikers te raken."],
    causes: ["De bestaande releaseflow was buildgericht en niet blok-/accountgericht."],
    fixes: ["Feature-entitlements en BETA-only settings stripping toegevoegd; stable execution blijft legacy zolang een feature niet gepubliceerd is."],
    now: ["Build 403 levert de bijbehorende BETA UI en blokgewijze releasebediening."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-401-portfolio-koers-crossed-swords",
    version: "46",
    build: "401",
    releasedAt: "2026-09-22",
    title: "Portfolio Koers exact naar gekruiste-zwaarden referentie",
    newItems: ["Gekruiste LONG/SHORT-zwaarden, verhoogde badges, connectors en brede bevestigde equity-zonegebieden."],
    problems: ["De vorige soldaat-iconen en smalle zones waren visueel onvoldoende duidelijk."],
    causes: ["Build 400 gebruikte compactere symboliek en oorspronkelijke smalle zonebanden."],
    fixes: ["Alleen de displaylaag van Portfolio Koers is verfijnd; trading- en datalogica bleef ongewijzigd."],
    now: ["Build 401 blijft de visuele Portfolio Koers-basis waarop Build 402 verder bouwt."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-400-portfolio-koers-icon-markers",
    version: "46",
    build: "400",
    releasedAt: "2026-09-22",
    title: "Portfolio Koers: iconen, Bollinger-veilige markers en bredere mobiele plot",
    newItems: ["Icon-first LONG/SHORT/TP-markers, 48px prijsas en vaste 15m-openingsview."],
    problems: ["Soldaat-icoon bleek visueel onvoldoende duidelijk en de prijszones oogden nog te smal ten opzichte van de goedgekeurde referentie."],
    causes: ["Build 400 optimaliseerde markerlogica en veiligheid maar gebruikte nog een compact soldaat-symbool en de oorspronkelijke smalle zonebanden."],
    fixes: ["Bollinger-veilige markerplaatsing, detailtooltips en timeframe-specifieke openingsranges ingevoerd."],
    now: ["Build 401 vervangt alleen de visuele symboliek en zonepresentatie; de onderliggende data blijft gelijk."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-399-portfolio-koers-visible-zones",
    version: "46",
    build: "399",
    releasedAt: "2026-09-22",
    title: "Portfolio Koers: zichtbare zones en rustiger events",
    newItems: ["Dynamische zones zichtbaar vóór de chartcanvas en maximaal drie hoofdlabels/twee clusters."],
    problems: ["Prijsas en eventpresentatie namen mobiel nog te veel ruimte in; eventvakjes konden Bollinger-informatie blokkeren."],
    causes: ["Build 399 declutterde de chart, maar markers waren nog tekst-/kaartgebaseerd en hielden geen harde Bollinger-envelopegrens aan."],
    fixes: ["Zichtbare zones, strengere densitylimieten en subtielere eventlaag ingevoerd."],
    now: ["Build 400 vervolgt uitsluitend de visuele laag met iconen, smallere prijsas en Bollinger-veilige markerplaatsing."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-398-portfolio-koers-visual-calm",
    version: "46",
    build: "398",
    releasedAt: "2026-09-22",
    title: "Portfolio Koers rust, zones en eventclustering",
    newItems: ["Maximaal vijf volledige labels, collision-aware clustering en prijsgebonden zonekleuren."],
    problems: ["Eventlabels konden de chart nog domineren en de zonekleuren bleken achter de opaque canvas te staan."],
    causes: ["De eerste visual-calm pass beperkte labeldichtheid maar niet alle markerlagen; zone z-index stond te laag."],
    fixes: ["Pure marker-layouthelper, compactere events en prijsgebaseerde zoneberekening toegevoegd."],
    now: ["Build 399 vervolgt dit uitsluitend visueel met zichtbare zones en strengere densitylimieten."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-397-startup-root-cause",
    version: "46",
    build: "397",
    releasedAt: "2026-09-22",
    title: "Startup-incident: chart-provider en PWA-lifecycle hersteld",
    newItems: ["Chart/Snapshot lifecycle binnen AuthProvider en passieve PWA-startup."],
    problems: ["Meerdere gebruikers konden zwart scherm/spinner en sessieherstart zien."],
    causes: ["Build 395 chartprovider-scope en disruptieve PWA-takeover."],
    fixes: ["AuthProvider-scope en service-worker lifecycle hersteld."],
    now: ["Build 398 raakt deze startup/auth/PWA-laag bewust niet aan."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-396-pwa-startup-loop",
    version: "46",
    build: "396",
    releasedAt: "2026-09-22",
    title: "Eerste PWA-opstartstabilisatie",
    newItems: ["Een deel van de automatische PWA-reloadpaden tijdens startup werd verwijderd en begrensd."],
    problems: ["De app kon tijdens sessieherstel meerdere keren herladen."],
    causes: ["Manifest-, service-worker- en canonical-buildnavigatie konden elkaar overlappen."],
    fixes: ["controllerchange-reload en directe initial canonical navigatie zijn verwijderd."],
    now: ["Build 397 vult dit aan met de gevonden chart/AuthProvider-root cause en volledig passieve service-worker takeover."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-395-portfolio-koers-visual-parity",
    version: "46",
    build: "395",
    releasedAt: "2026-09-22",
    title: "Portfolio Koers visueel naar de goedgekeurde referentie",
    newItems: [
      "Blauw-neon Portfolio Koers-layout, echte lokale Aster-equityhistorie als veilige displayaanvulling, bevestigde eventlabels en extra Snapshot-context.",
    ],
    problems: ["Build 394 was functioneel correct maar week visueel nog sterk af van de goedgekeurde referentie."],
    causes: ["De eerste chartrelease prioriteerde veilige datakoppeling boven visuele parity."],
    fixes: ["Layout, Bollinger-presentatie, markers, history-merge en mobiele detailpresentatie zijn herbouwd zonder synthetische tradegegevens."],
    now: ["Build 395 is de visuele chartbasis; Build 396 verandert alleen de PWA-opstartstabiliteit."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-394-portfolio-koers-sync",
    version: "46",
    build: "394",
    releasedAt: "2026-09-22",
    title: "Portfolio Koers en Portfolio Snapshot exact gesynchroniseerd",
    newItems: ["De actuele chartwaarde gebruikt exact dezelfde zichtbare Aster-equity als Portfolio Snapshot."],
    problems: ["Build 393 kon tijdelijk een andere actuele equity in de chart tonen dan in Portfolio Snapshot."],
    causes: ["De aparte chart-response kon de reeds zichtbare Snapshot-equity opnieuw overschrijven."],
    fixes: ["Portfolio Snapshot-equity werd leidend voor chartheader en actuele candle-close."],
    now: ["Build 394 is de functionele synchronisatiebasis voor de visuele parity-release Build 395."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-393-portfolio-koers",
    version: "46",
    build: "393",
    releasedAt: "2026-09-22",
    title: "Portfolio Koers live boven Portfolio Snapshot",
    newItems: [
      "Persistente Portfolio Koers-kaart met echte portfolio-equity OHLC-candles, Bollinger 20,2, dynamische zones, markers, timeframes en fullscreen.",
    ],
    problems: ["Portfolioverloop was nog niet als persistente analysegrafiek direct boven Portfolio Snapshot beschikbaar."],
    causes: ["Er was nog geen account-scoped serverpersistente Portfolio Koers-dataset gekoppeld aan de mobiele Aster-weergave."],
    fixes: ["Read-only chart-backend en aparte frontend-kaart toegevoegd zonder Portfolio Snapshot of tradingexecutie te vervangen."],
    now: ["Build 393 introduceerde de nieuwe Portfolio Koers-module; Build 394 synchroniseert de actuele displaywaarde exact met Portfolio Snapshot."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-392-independent-slot-controls",
    version: "46",
    build: "392",
    releasedAt: "2026-09-21",
    title: "LONG en SHORT-stoelen onafhankelijk instelbaar",
    newItems: [
      "LONG slots en SHORT slots kunnen nu ieder rechtstreeks worden verhoogd of verlaagd zonder eerst Totaal posities aan te passen.",
      "Totaal posities wordt automatisch opnieuw berekend als de som van de twee zijden.",
    ],
    problems: [
      "Wie bijvoorbeeld van 35 naar 45 LONG-stoelen wilde, moest eerst het totaal verhogen en daarna opnieuw onthouden en instellen hoeveel SHORT-stoelen moesten blijven staan.",
      "Een wijziging aan één zijde veranderde voorheen impliciet de andere zijde omdat het totaal als vaste waarde werd behandeld.",
    ],
    causes: [
      "De slot-helper hield Totaal posities vast en berekende de tegenoverliggende zijde als restwaarde.",
    ],
    fixes: [
      "Bij een LONG-wijziging blijft het actuele aantal SHORT-stoelen exact staan en volgt Totaal posities automatisch LONG + SHORT.",
      "Bij een SHORT-wijziging blijft het actuele aantal LONG-stoelen exact staan en volgt Totaal posities automatisch LONG + SHORT.",
      "De bestaande harde limiet van 100 totale posities blijft behouden; alleen de gewijzigde zijde wordt zo nodig begrensd.",
      "Regressietests bewaken zowel de rekenregel als de koppeling in Botinstellingen, inclusief de bestaande blur/commit-flow.",
    ],
    now: [
      "35 LONG + 30 SHORT → LONG naar 45 geeft direct 45 LONG + 30 SHORT = 75 totaal.",
      "45 LONG + 30 SHORT → SHORT naar 20 geeft direct 45 LONG + 20 SHORT = 65 totaal.",
      "De gebruiker hoeft de niet-aangepaste zijde niet meer opnieuw in te voeren of te onthouden.",
    ],
    before: "LONG of SHORT wijzigen hield het totaal vast en schoof daardoor automatisch de andere zijde mee.",
    after: "LONG en SHORT zijn onafhankelijke invoervelden; alleen het gewijzigde veld verandert en het totaal volgt automatisch.",
    technicalDetails: [
      "Aangepast in web/components/aster-strategy2-maker.tsx, web/lib/position-slot-input.ts en de bijbehorende regressiecontracten.",
      "Geen scanner-, Bollinger-, leverage-, DCA-, TP-, order- of exchange-executionlogica gewijzigd.",
      "Bestaande opgeslagen LONG/SHORT-instellingen en actieve posities worden niet automatisch gewijzigd door deze release.",
    ],
    confidence: "confirmed",
  },
  {
    id: "v46-build-390-sizing-isolation",
    version: "46",
    build: "390",
    releasedAt: "2026-09-21",
    title: "Strategy-2 sizingmodus beschermd tegen oude UI-state",
    newItems: [
      "Botinstellingen vergelijken bevestigde UI-state voortaan met de nieuwste server-configVersion voordat instellingen opnieuw worden geladen.",
      "Opslaan en Starten lezen vlak vóór verzending de actuele serverinstellingen en bewaren de server-side positieomvangmodus tenzij de gebruiker de schakelaar Vaste positieomvang expliciet heeft gewijzigd.",
    ],
    problems: [
      "Een eerder bevestigde browserstate kon nieuwer serverherstel blijven overschrijven en daardoor entrySizingMode opnieuw op notional zetten.",
      "Bij Top-350 en vrije LONG-stoelen kon dit geldige 1m Bollinger-kandidaten alsnog blokkeren doordat een kleine vaste notional tegen de minimale Aster-order botste.",
    ],
    causes: [
      "strategy2ServerStatus gaf iedere lokale confirmedState onbeperkt voorrang, ook wanneer de server inmiddels een hogere configVersion had.",
      "De Botinstellingen stuurden entrySizingMode bij iedere gewone save/start opnieuw mee vanuit die mogelijk verouderde schakelaarstate.",
    ],
    fixes: [
      "Een server-snapshot met een hogere configVersion vervangt nu automatisch een oudere confirmedState.",
      "De positieomvangmodus wordt bij save/start tegen een no-store server-snapshot gereconcilieerd; alleen een expliciete interactie met Vaste positieomvang mag margin/notional wijzigen.",
      "Nieuwe regressietests bewaken zowel server-versiefreshness als isolatie van de sizingmodus bij overige instellingen.",
    ],
    now: [
      "Wijzigingen aan slots, Top-N, Portfolio TP, Bollinger-timeframe of andere Botinstellingen kunnen een gerepareerde marginmodus niet meer stil terugzetten naar notional.",
      "De schakelaar Vaste positieomvang blijft wel volledig bruikbaar wanneer de gebruiker hem bewust zelf aan- of uitzet.",
      "Deze release verandert geen bestaande positie, order, DCA-state of actuele accountinstelling automatisch.",
    ],
    before: "Een stale browser-confirmatie kon een nieuwere serverconfig negeren en later opnieuw als notional opslaan.",
    after: "De nieuwste serverconfig is leidend en sizing verandert alleen na een expliciete gebruikeractie op de sizing-schakelaar.",
    technicalDetails: [
      "Aangepast in web/lib/aster-strategy2-server-status.mjs en web/components/aster-strategy2-maker.tsx.",
      "De publieke Aster-controle vond tijdens diagnose 44 actuele LONG-signalen binnen Top-350 op 1m; de marktvoorwaarde zelf was dus niet de primaire blokkade.",
      "Geen backend tradingformule, Bollingerberekening, leverage-resolver of order-executionpad is door deze webrelease aangepast.",
      "Build 390 behoudt bestaande Profit Lock- en Sniper-historiecontracten; de Sniper-regressietest valideert voortaan toekomstvast in plaats van één hardcoded buildnummer.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-389-portfolio-tp-additive",
    version: "46",
    build: "389",
    releasedAt: "2026-09-21",
    title: "Portfolio TP behoudt per-trade Take Profit",
    newItems: [
      "Portfolio Take Profit werkt nu aanvullend op de bestaande LONG/SHORT Take Profit per positie.",
      "De portfolio-doelwaarde sluit nog steeds alle posities zodra het portfoliodoel wordt bereikt.",
    ],
    problems: [
      "Wanneer Take Profit op Portfolio stond, werd de normale pair-level Take Profit volledig uitgeschakeld.",
      "Daardoor konden winstgevende individuele LONG/SHORT-posities hun eigen ingestelde TP passeren zonder automatisch te sluiten.",
    ],
    causes: [
      "De webapp schreef takeProfitEnabled=false zodra de modus niet PER_TRADE was.",
      "De Multi BB runtime en de portfolio-orderguard behandelden PORTFOLIO ten onrechte als een exclusieve TP-modus en blokkeerden individuele mbb-tp closes.",
    ],
    fixes: [
      "PORTFOLIO houdt takeProfitEnabled nu actief; alleen OFF schakelt individuele TP uit.",
      "De pair-aware runtime blijft in PORTFOLIO mode de LONG/SHORT TP-waarden toepassen.",
      "De last-millisecond portfolio guard staat individuele TP-closes toe zolang de portfolio-exit zelf niet actief is; bij bereikt portfolio-doel behoudt de volledige portfolio-exit prioriteit.",
    ],
    now: [
      "PER_TRADE: individuele LONG/SHORT TP actief.",
      "PORTFOLIO: individuele LONG/SHORT TP actief én volledige portfolio-close op het ingestelde portfoliodoel.",
      "OFF: individuele en portfolio Take Profit uit.",
    ],
    before: "Portfolio mode schakelde de individuele pair Take Profit uit.",
    after: "Portfolio mode is additief: pair TP blijft werken en het portfolio-doel sluit daarnaast alles zodra dat doel wordt bereikt.",
    technicalDetails: [
      "Aangepast in web/components/aster-strategy2-maker.tsx, cloud_api/aster_multi_bb.py en cloud_api/aster_multi_bb_portfolio.py.",
      "Profit Lock Ladder behoudt zijn bestaande expliciete TP-suppressie; deze fix verandert die aparte strategie niet.",
      "Geen DCA-, Bollinger-, leverage-, slot- of Stoploss-regel is door deze release gewijzigd.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-388-slot-capacity-release-history",
    version: "46",
    build: "388",
    releasedAt: "2026-09-21",
    title: "Portfolio Snapshot toont echte slotcapaciteit",
    newItems: [
      "Portfolio Snapshot toont nu per zijde zowel actieve posities als de ingestelde LONG/SHORT-capaciteit.",
      "De compacte status gebruikt dezelfde zichtbare Slot-overzicht-bron als Botinstellingen en behoudt de bestaande actieve-positiesbron als fallback.",
    ],
    problems: [
      "Na het verhogen van LONG-slots van 30 naar 35 bleef Portfolio Snapshot alleen 30L / 30S tonen.",
      "Daardoor leek de portefeuille visueel volledig bezet terwijl Botinstellingen correct 30 / 35 LONG en 5 vrije LONG-stoelen aangaf.",
    ],
    causes: [
      "De compacte Portfolio Snapshot las alleen actieve LONG/SHORT-aantallen uit de legacy Active Trades Index en kende de ingestelde zijde-capaciteit niet.",
    ],
    fixes: [
      "Portfolio Snapshot leest nu de actuele LONG- en SHORT-teller uit het bestaande Slot-overzicht, inclusief ingestelde capaciteit.",
      "De status toont bijvoorbeeld 30/35L / 30/30S zodat vrije capaciteit direct zichtbaar is.",
      "Als het Slot-overzicht tijdelijk nog niet beschikbaar is, blijft de bestaande actieve LONG/SHORT-weergave als veilige fallback functioneren.",
    ],
    now: [
      "Actieve positie-aantallen en ingestelde stoelcapaciteit zijn in Portfolio Snapshot niet langer met elkaar te verwarren.",
      "Deze wijziging raakt uitsluitend de webpresentatie; scanner-, Bollinger-, order-, DCA-, TP- en exchange-logica blijven ongewijzigd.",
    ],
    before: "Portfolio Snapshot toonde alleen 30L / 30S en kon daardoor volledig gevuld lijken terwijl 5 LONG-stoelen vrij waren.",
    after: "Portfolio Snapshot toont actieve/beoogde capaciteit per zijde, bijvoorbeeld 30/35L / 30/30S.",
    technicalDetails: [
      "Bron voor capaciteit: bestaand Botinstellingen Slot-overzicht, dat sinds Build 382 Aster exchange-truth voor bezetting gebruikt.",
      "Fallback blijft de bestaande Active Trades Index zodat de Snapshot niet leegvalt wanneer de instellingencomponent nog niet gemount is.",
      "Geen accountinstelling, positie, order of strategieparameter wordt door deze release gewijzigd.",
    ],
    confidence: "confirmed",
  },
  {
    id: "v46-build-387-profit-close-release-history",
    version: "46",
    build: "387",
    releasedAt: "2026-09-21",
    title: "Portfolio winstknoppen gelijkgetrokken + fixes zichtbaar",
    newItems: [
      "Alle productiefixes worden voortaan ook als afzonderlijke, zichtbare release-notitie in Versiegeschiedenis opgenomen.",
      "Deze release documenteert de live backendfix waardoor Portfolio Snapshot en Tradecentrum dezelfde Multi BB-winstposities herkennen.",
    ],
    problems: [
      "Tradecentrum kon bijvoorbeeld 5 winstposities en +$17,57 tonen, terwijl Portfolio Snapshot tegelijk Close Long/Short/All op 0 posities en US$ 0,00 zette.",
      "Daardoor gaf één scherm twee verschillende antwoorden over exact dezelfde open Aster-posities.",
    ],
    causes: [
      "De veilige Strategy-2 profit-close gebruikte legacy ownedLegs als ownershipbron, terwijl de actieve Multi BB-engine haar beheerde posities in multiBbPositions bijhoudt.",
      "De live Tradecentrum-lijst zag de Aster-posities wel, maar de profit-close preview verloor Multi BB-posities tijdens de ownershipfilter.",
    ],
    fixes: [
      "De Strategy-2 ownershipresolver neemt nu ook geldige bot-managed LONG/SHORT-legs uit multiBbPositions mee.",
      "De bestaande Strategy-2/Sniper scheiding blijft intact: deze wijziging maakt Sniper-posities niet sluitbaar via de Aster Multi BB-profitknoppen.",
      "Vlak vóór iedere daadwerkelijke profit-close wordt de Aster-positie opnieuw gelezen en moet de positie nog steeds aan de winstgrens voldoen.",
      "De volledige backendtestset, candidate-healthcheck en productiecontrole zijn vóór en na promotie geslaagd.",
    ],
    now: [
      "Portfolio Snapshot Close Long, Close Short en Close All herkennen dezelfde beheerde Multi BB-posities als Tradecentrum.",
      "Een winstpositie verdwijnt niet meer uit Portfolio Snapshot alleen omdat deze via Multi BB-runtimeownership in plaats van legacy ownedLegs wordt beheerd.",
      "Build 386 SNIPER Live Trading blijft volledig behouden; Build 387 voegt deze fixregistratie en zichtbare release-notitie toe.",
    ],
    before: "Tradecentrum en Portfolio Snapshot konden voor dezelfde Aster-accountpositie verschillende winst-aantallen tonen.",
    after: "Multi BB-posities worden in de veilige Strategy-2 profit-close correct als owned herkend, terwijl Sniper-isolatie behouden blijft.",
    technicalDetails: [
      "Backendfix commit: b2f20b6e924a8a71d8c2d7f3986c96d74daf4cf2.",
      "Live backendrevision na verificatie: tradementor-api-src-b2f20b6e-249023.",
      "Geen bestaande positie is door deze release automatisch gesloten; alleen herkenning, preview en expliciet bevestigde profit-close scope zijn gecorrigeerd.",
    ],
    confidence: "confirmed",
  },

  {
  id: "v46-build-386-sniper-live",
  version: "46",
  build: "386",
  releasedAt: "2026-09-21",
  title: "SNIPER Live Trading",
  newItems: [
    "Nieuw hoofdtabblad SNIPER tussen ASTER en NIEUWS met eigen Overzicht, Trades, Signalen, Prestaties en Instellingen.",
    "Sniper kan na expliciete live-bevestiging echte Aster USDT-perpetual orders plaatsen en beheren.",
    "Aster en Sniper delen portfolio/equity, available margin en account-risk, maar hebben volledig gescheiden scanners, trades, slots en normale close-acties.",
    "Een atomische symbol lock voorkomt dat Aster en Sniper ooit tegelijk dezelfde munt beheren, ongeacht LONG/SHORT-richting.",
  ],
  problems: [
    "De eerdere Sniper-build was alleen simulation-only en stond buiten de actuele productie-app.",
    "Zonder harde strategy ownership kon een Aster bulk-close theoretisch ook een Sniper-positie meenemen wanneer beide engines dezelfde exchange-accountdata gebruikten.",
    "Een gedeelde scanner/capaciteitsflow mocht nooit opnieuw leiden tot meerdere strategieën die dezelfde munt of extra stoelen claimen.",
  ],
  causes: [
    "De oude Aavansh Sniper-interface had bewust geen productie-execution backend.",
    "Aster exchange-position rows bevatten van zichzelf geen TradeMentor strategy-owner; ownership moet daarom vóór iedere entry intern en atomisch worden vastgelegd.",
  ],
  fixes: [
    "Sniper heeft een eigen live runtime, scannerstate, tradeledger, historie, settings en schedulerpad gekregen.",
    "Strategy-2 en Sniper gebruiken symbol-level ownership: ASTER.activeSymbols en SNIPER.activeSymbols mogen nooit overlappen.",
    "Aster Close Profits >= $0,50 selecteert alleen bewezen Aster-owned symbols; Sniper exits raken alleen bewezen Sniper trades.",
    "De algemene Close All blijft bewust accountbreed: eerst emergency lock en beide bots UIT, daarna alle posities sluiten en exchange-flat verifiëren.",
    "Pending/unknown orders blijven fail-closed en worden eerst via exchange-reconciliation hersteld voordat een nieuwe order is toegestaan.",
    "Een accountbrede execution coordinator voorkomt dat Aster en Sniper gelijktijdig dezelfde verouderde available margin reserveren.",
    "De eerste echte Sniper-activering is geblokkeerd achter een zeer kleine open/fill/close Aster-canary; de scanner wordt pas daarna ingeschakeld.",
    "Gesloten Sniper-trades gebruiken exchange-bevestigde realized PnL, fees en funding voor hun netto resultaat.",
  ],
  now: [
    "Sniper staat tussen Aster en Nieuws en toont uitsluitend eigen posities, signalen, historie en performance.",
    "Aster-posities worden niet als Sniper-trades getoond en Sniper-symbols worden niet als beheerbare Aster-posities weergegeven.",
    "De gedeelde portfolio- en available waarden blijven in beide strategieën zichtbaar, terwijl normaal positiebeheer volledig gescheiden blijft.",
  ],
  before: "Sniper bestond als aparte simulation-only prototypebuild en was niet bruikbaar voor echte orders in de actuele productie-app.",
  after: "Sniper is als tweede geïsoleerde live Aster-engine in V46 geïntegreerd, met symbol ownership, eigen tradebeheer en accountbrede noodstop.",
  technicalDetails: [
    "Primaire visuele referentie: https://chatgpt.com/s/m_6aab179ba6008191b3b874803a1508ab.",
    "Aanvullende goedgekeurde referenties: 3b80f501-69c7-424a-bb80-9aff04bb7594, 0cee1df2-8608-4a48-9e7d-1421d4ff3177, e6590034-d49b-485f-a581-53fc605b11ea, de872ec8-e8c9-4ffa-af9e-e35970c35c93, a1138afd-dd0f-46ec-be4e-eb7302ba181f, 25ca0d1c-4e95-473b-b1de-311e75a0f3f4, e8366e61-315b-4016-a02e-a23736fc59ea en 3548d2b7-c1d8-494b-b0c2-c588505a6b7c.",
    "Bestaande prototypebasis: aavansh-sniper-build372 / web/components/sniper-dashboard.tsx.",
    "Historische Sniper-replay modelleert fees, spread, slippage, next-bar latency en stop-first bij onzekere intrabar-volgorde; ontbrekende historische orderbook/orderflow-data wordt expliciet als beperking gemeld.",
    "Fault/recovery-tests dekken onder meer onzekere submissions, pending open/close recovery, timeout-exits, symbol overlap, strategy-scoped bulk close en accountbrede noodstop.",
    "De beperkte live canary is een harde runtime-gate bij de eerste live activering; de versiegeschiedenis wordt niet als bewijs van een reeds uitgevoerde canary gebruikt.",
  ],
  confidence: "confirmed",
},

  {
    id: "v46-build-385-aster-realtime-equity",
    version: "46",
    build: "385",
    releasedAt: "2026-09-21",
    title: "Aster portefeuillewaarde volgt realtime markprijzen",
    newItems: [
      "De Aster portefeuillewaarde beweegt nu mee met de bestaande realtime markprijs-feed in plaats van te wachten op de volgende volledige accountsnapshot.",
      "De bestaande realtime positie-PnL wordt direct doorvertaald naar de zichtbare equity.",
    ],
    problems: [
      "Na het herstellen van de Aster-data konden markprijzen en open PnL al live bewegen, terwijl de totale portefeuillewaarde nog op de laatste server-snapshot bleef staan.",
      "Daardoor kon de Aster-app tijdelijk een iets hogere of lagere accountwaarde tonen dan Webapp 46.",
    ],
    causes: [
      "De realtime reducer werkte positieprijzen en unrealized PnL bij, maar liet het top-level equity-veld ongewijzigd tot de volgende gesigneerde accountrefresh.",
    ],
    fixes: [
      "Realtime equity wordt voortaan berekend als bevestigde walletBalance plus de opnieuw berekende totale unrealized PnL.",
      "Als walletBalance tijdelijk ontbreekt, gebruikt de client alleen de bevestigde equity plus het verschil in unrealized PnL als veilige fallback.",
      "Available balance, positie-openingen/sluitingen en orderstate blijven bewust server-confirmed en worden niet door de browser verzonnen.",
    ],
    now: [
      "Bij normale marktbewegingen volgt de zichtbare Aster-equity de realtime markfeed in dezelfde 250 ms renderbatch als de positie-PnL.",
      "Volledige account- en ordertruth blijft periodiek door de Aster API worden bevestigd.",
    ],
    before: "De realtime stream veranderde markprijzen en positie-PnL, maar de totale equity bleef staan tot een latere accountsnapshot.",
    after: "Markprijs, open PnL en zichtbare equity bewegen samen; volledige accounttruth blijft door Aster bevestigd.",
    technicalDetails: [
      "Alleen web-presentatie/state-afleiding en regressietests gewijzigd; geen order-, DCA-, TP-, wallet- of backend-executionlogica aangepast.",
      "De browser wijzigt geen beschikbare marge op basis van een schatting; availableBalance blijft Aster API-truth.",
    ],
    confidence: "confirmed",
  },
  {
    id: "v46-build-384-portfolio-cycle",
    version: "46",
    build: "384",
    releasedAt: "2026-09-21",
    title: "Portfolio Cyclus zichtbaar in Portfolio Snapshot",
    newItems: [
      "Portfolio Snapshot heeft nu permanent een compact Portfolio Cyclus-vak in de bestaande vrije ruimte rechts van Profit sparen.",
      "Zonder actieve Portfolio Take Profit op portfoliowaarde toont het vak Niet ingesteld, Portfolio TP niet actief en Instellen.",
      "Met actieve Portfolio Take Profit op portfoliowaarde toont het vak live voortgang, resterend bedrag, resterend percentage en een duidelijke status.",
    ],
    problems: [
      "De Portfolio TP-cycle was functioneel aanwezig, maar de gebruiker kon in Portfolio Snapshot niet direct zien hoe ver de huidige cyclus van sluiting verwijderd was.",
      "Een zichtbaar cyclusnummer zonder duidelijke startbasis gaf onnodige verwarring.",
    ],
    causes: [
      "De compacte Portfolio Snapshot had nog geen vaste presentatiecomponent die de server-side Portfolio TP-cycle naar een duidelijke voortgangsstatus vertaalde.",
    ],
    fixes: [
      "Het bestaande lege derde vak naast Profit sparen is gevuld zonder de overige Portfolio Snapshot-layout te herschikken.",
      "De actieve state gebruikt de bestaande server-side Portfolio TP-cycledata voor basiswaarde, doelwaarde en actuele equity.",
      "De tegel toont geen cyclusnummer en valt buiten Portfolio-modus altijd terug op de nette Niet ingesteld-state.",
      "Klikken op het vak brengt de gebruiker naar de bestaande Portfolio Take Profit-instellingen.",
    ],
    now: [
      "Portfolio Cyclus is altijd zichtbaar op dezelfde vaste plek.",
      "Alleen Portfolio Take Profit in modus Portfolio activeert de live voortgangsweergave.",
      "De tegel verzint geen cyclusdata: zonder geldige server-cycle blijft de inactive state zichtbaar.",
    ],
    before: "De vrije ruimte rechts van Profit sparen gaf geen bruikbare status van de actieve Portfolio TP-cycle.",
    after: "Diezelfde bestaande ruimte toont nu compact of Portfolio TP niet is ingesteld, of hoe dicht de actieve Portfolio TP-cycle bij sluiten is.",
    technicalDetails: [
      "Visuele referentie inactive state: file_00000000192481f495e9311d4ed77933.",
      "Visuele referentie active state: file_00000000b78081f4a8a332da9a783f3b.",
      "De overige Portfolio Snapshot-cards, tradinglogica, DCA-logica, open posities en orders zijn niet gewijzigd.",
    ],
    confidence: "confirmed",
  },
  {
    id: "v46-build-383-fixed-position-size-isolation",
    version: "46",
    build: "383",
    releasedAt: "2026-09-21",
    title: "Vaste positieomvang raakt basisinstap niet meer",
    newItems: [
      "Instap LONG/SHORT · margin blijft altijd zichtbaar en behoudt exact de opgeslagen waarde.",
      "Vaste positieomvang gebruikt voortaan aparte LONG/SHORT positievelden in USDT.",
      "Een vaste positie moet expliciet worden ingevuld; margin wordt nooit meer automatisch met leverage vermenigvuldigd.",
    ],
    problems: [
      "Bij het inschakelen van Vaste positieomvang kon de webapp een oude margin van bijvoorbeeld 0,30 automatisch tonen als 6 USDT bij 20x.",
      "Daardoor leek een bestaande basisinstelling gewijzigd, terwijl 6 USDT notional een wezenlijk andere instelling is dan 0,30 USDT margin.",
    ],
    causes: [
      "De Build-380 UI gebruikte legacy entryNotionalUsd en als fallback margin × minimum leverage om notionalvelden vooraf te vullen.",
      "Hetzelfde LONG/SHORT invoervak wisselde bovendien tussen margin en positie, waardoor de twee onafhankelijke instellingen visueel als één waarde leken.",
    ],
    fixes: [
      "De leverage-vermenigvuldiging is volledig uit de UI-loadmigratie verwijderd.",
      "Margin- en notionalwaarden zijn nu afzonderlijke velden; het activeren van Vaste positieomvang overschrijft de marginvelden niet.",
      "In marginmodus worden bestaande notionalvelden niet opnieuw geschreven.",
      "Bij een lege vaste positie blokkeert opslaan/starten met een expliciete melding in plaats van een automatische omrekening.",
    ],
    now: [
      "0,30 margin blijft 0,30 margin, ongeacht of een markt 20x, 50x, 100x of 300x ondersteunt.",
      "Wie Vaste positieomvang wil gebruiken moet de gewenste positie-USDT apart en bewust invullen.",
      "DCA, Portfolio TP, Stoploss, leveragefilters en bestaande actieve posities worden door deze UI-fix niet aangepast.",
    ],
    before: "Vaste positieomvang kon automatisch afgeleide notionalwaarden tonen en opslaan op basis van margin × minimum leverage.",
    after: "Basis-margin en vaste positieomvang zijn strikt gescheiden; geen automatische conversie of overschrijving meer.",
    technicalDetails: [
      "Regressietests bewaken dat legacy marginwaarden nooit via minimum leverage in notional worden omgezet.",
      "De bestaande server-side execution mode blijft leidend; deze release verandert geen open posities of orders.",
    ],
    confidence: "confirmed",
  },

  {
    id: "v46-build-382-slot-truth",
    version: "46",
    build: "382",
    releasedAt: "2026-09-20",
    title: "Portfolio Cycle snapshot + juiste slotbezetting",
    newItems: [
      "Portfolio Snapshot toont het nieuwe Portfolio Cycle-vak uit de actuele Portfolio TP-cycle.",
      "Het Slot-overzicht in Botinstellingen gebruikt dezelfde actuele Aster-posities als Portfolio Snapshot.",
    ],
    problems: ["Slot-overzicht kon vrije LONG-stoelen tonen terwijl Aster al volledig bezet was."],
    causes: ["De balkjes gebruikten primair Strategy-2 ownership-state in plaats van actuele Aster-posities."],
    fixes: ["LONG, SHORT en totaal bezet/vrij gebruiken nu Aster exchange-truth met Strategy-2 als fallback."],
    now: ["30 LONG + 30 SHORT toont 30/30, 30/30, 60/60 en 0 vrij."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-381-portfolio-tp-2",
    version: "46",
    build: "381",
    releasedAt: "2026-09-20",
    title: "Portfolio Take Profit 2.0",
    newItems: [
      "Portfolio Take Profit kan nu als percentage of als vast dollar-winstbedrag worden ingesteld.",
      "De gebruiker kiest de berekeningsbasis: Cycle start, een eenmalig vastgezette huidige waarde of een aangepaste basiswaarde.",
      "Reset cycle zet alleen de Portfolio TP-cycle start naar de actuele Aster-equity en verstuurt daarbij nul orders.",
      "Per trade, Portfolio en Uit tonen voortaan een duidelijke goudkleurige actieve state.",
    ],
    problems: [
      "Portfolio TP kon alleen procentueel worden ingesteld en rekende altijd vanaf de bestaande cycle start.",
      "De drie Take Profit-modusknoppen waren visueel te gelijk.",
    ],
    causes: [
      "De bestaande Portfolio TP-configuratie kende alleen portfolioTpPercent en cycleStartEquity.",
      "De compacte tabstyling gebruikte een subtiele statuskleur in plaats van een expliciete geselecteerde state.",
    ],
    fixes: [
      "Nieuwe persistente inputMode, value, baseMode en customBaseEquity toegevoegd met backward-compatible migratie.",
      "Huidige waarde wordt server-side één keer vastgezet per opgeslagen configuratie.",
      "Na een succesvolle Portfolio TP wordt de werkelijke post-close equity de nieuwe cycle start.",
    ],
    now: [
      "Portfolio TP ondersteunt %/$, drie basiskeuzes, veilige cycle reset en automatische post-close cycli.",
    ],
    confidence: "confirmed",
  },
  {
    id: "v46-build-380-fixed-position-size",
    version: "46",
    build: "380",
    releasedAt: "2026-09-20",
    title: "Vaste positieomvang als optionele instapmodus",
    newItems: [
      "Nieuwe schakelaar Vaste positieomvang: instapbedrag kan optioneel de werkelijke LONG/SHORT positie in USDT zijn in plaats van margin.",
      "LONG en SHORT bewaren ieder hun eigen positieomvang en de benodigde margin wordt per markt uit de werkelijk gekozen leverage afgeleid.",
    ],
    problems: ["Bij gelijke margin kregen markten met verschillende leverage verschillende werkelijke positieomvang."],
    causes: ["Build 379 stuurde de compacte LONG/SHORT instapvelden expliciet als entrySizingMode=margin."],
    fixes: ["Vaste positieomvang gebruikt de server-authoritative notional resolver terwijl het bestaande margin-gedrag beschikbaar blijft."],
    now: ["Gebruikers kunnen per account kiezen tussen vaste positieomvang en vaste margin."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-379-compact-settings-maxlev-stoploss",
    version: "46",
    build: "379",
    releasedAt: "2026-09-20",
    title: "Compacte Botinstellingen met Maximum leverage en Stoploss",
    newItems: ["Compact premium Botinstellingen, optionele Maximum leverage en server-side Stoploss."],
    problems: ["Botinstellingen waren te ruim en leverage had nog geen optionele bovengrens."],
    causes: ["Bestaande UI en leverage-resolver waren voor de nieuwe compacte instellingen nog niet samengebracht."],
    fixes: ["Slot-overzicht, Maximum leverage en Stoploss zijn toegevoegd zonder bestaande posities te resetten."],
    now: ["Dit is de directe voorganger van build 380."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-375-long-refill",
    version: "46",
    build: "375",
    releasedAt: "2026-09-19",
    title: "Vrije LONG-slots niet meer geblokkeerd door verborgen oude hedge-modus",
    newItems: ["Normale Botinstellingen wissen voortaan expliciet de oude verborgen asymmetric-pairmodus bij Opslaan, Simuleren en Starten."],
    problems: ["Een gebruiker kon vrije LONG-slots hebben terwijl geen LONG-instap plaatsvond, doordat een niet-zichtbare oude asymmetric hedge-instelling nog actief bleef."],
    causes: ["De normale Botinstellingen bouwden nieuwe settings bovenop alle eerder opgeslagen velden, waardoor asymmetricHedgeModeEnabled=true onzichtbaar behouden kon blijven."],
    fixes: ["Normale Multi DCA-instellingen sturen asymmetricHedgeModeEnabled nu expliciet als false.", "Regressietests bewaken dat de verborgen paired-entrymodus niet opnieuw wordt meegenomen door een normale save/start."],
    now: ["Vrije LONG- en SHORT-capaciteit wordt weer volgens de zichtbare instellingen behandeld."],
    before: "Een oude verborgen asymmetricHedgeModeEnabled=true kon vrije LONG-slots stil blokkeren.",
    after: "Normale Botinstellingen kunnen die verborgen paarmodus niet meer stilzwijgend vasthouden.",
    technicalDetails: ["Geen DCA-, TP-, order-, wallet-, WebSocket- of exchange-berekening gewijzigd."],
    confidence: "confirmed",
  },
  {
    id: "v46-build-374-hedge-card",
    version: "46",
    build: "374",
    releasedAt: "2026-09-19",
    title: "Hedge Dekking-kaart visueel vereenvoudigd",
    newItems: [
      "De Hedge Dekking-kaart sluit visueel rustiger aan op de overige Portfolio Snapshot-kaarten.",
    ],
    problems: [
      "De Hedge Dekking-kaart sprong te sterk uit en oude doelinformatie nam onnodig ruimte in.",
    ],
    causes: [
      "De compacte kaart toonde naast het actuele percentage ook een doelpercentage en statusbadge, met extra statuskleuren en glow.",
    ],
    fixes: [
      "Doelpercentage en doelstatusbadge zijn uit de compacte Hedge Dekking-kaart verwijderd.",
      "De kaart gebruikt nu een rustige donkere basis met subtiele goud/groene accenten zonder overdreven glow.",
      "De bestaande realtime hedge-dekkingberekening en het openen van de detailweergave zijn ongewijzigd gebleven.",
    ],
    now: [
      "De compacte kaart toont alleen het schild, HEDGE DEKKING en het actuele percentage.",
      "Waarden boven 100% blijven op mobiel en desktop binnen de kaart zonder overlap.",
    ],
    before: "De kaart toonde onder meer Doel 80% en een status zoals Boven doel en kreeg daardoor een opvallende alarmkaart-uitstraling.",
    after: "De kaart toont rustig het actuele hedgepercentage in dezelfde visuele hiërarchie als de omliggende Portfolio Snapshot-kaarten.",
    technicalDetails: [
      "Alleen webpresentatie, CSS, versieadministratie en regressietests gewijzigd; geen trading-, DCA-, order-, API-, WebSocket- of accountlogica.",
      "Visuele doelreferentie: file_00000000aa6c8210baf1b0ac8f94d18e.",
      "Responsive gedrag gecontroleerd via bestaande 640px- en 380px-layoutcontracten.",
    ],
    confidence: "confirmed",
  },
  {
    id: "v46-build-373-release-history",
    version: "46",
    build: "373",
    releasedAt: "2026-09-19",
    title: "Versiegeschiedenis en app-ontwikkellogboek",
    newItems: [
      "Mobiele versiegeschiedenis met nieuwste release bovenaan.",
      "Ongelezen badge bij de knop linksboven.",
      "Zoeken in oude releases, problemen en oplossingen.",
    ],
    problems: [
      "Gebruikers konden niet centraal terugvinden wat tussen appreleases veranderde en waarom.",
    ],
    causes: [
      "De bestaande versieknop controleerde alleen op updates; release-uitleg stond verspreid over commits, chats en technische notities.",
    ],
    fixes: [
      "Eén centrale releasebron toegevoegd met probleem, oorzaak, oplossing, voor/na en technische context per release.",
      "De linkerbovenhoek opent nu het mobiele ontwikkellogboek zonder de huidige pagina te verlaten.",
      "Buildnummer en releasehistorie zijn aan één releasecontract gekoppeld.",
    ],
    now: [
      "Nieuwe releases zijn direct herkenbaar en blijven later terugleesbaar.",
      "De gebruiker ziet hoeveel nieuwe builds nog niet zijn gelezen.",
      "Iedere volgende live webupdate moet een nieuw buildnummer én release-entry krijgen.",
    ],
    before: "De tekst CRYPTO BOT 2026 was statisch en de releasehistorie was niet vanuit de app bereikbaar.",
    after: "De linkerbovenhoek is een knop Versiegeschiedenis met een ongelezen teller en een volledig mobiel logboek.",
    technicalDetails: [
      "Alleen web-UI, versieadministratie en deploymentcontract gewijzigd.",
      "Leesstatus wordt lokaal en persistent in de PWA/browser opgeslagen; tradingstate wordt niet aangeraakt.",
      "Centrale bron: web/lib/release-history.ts.",
      "CI/deployment controleert buildnummer en release-entry vóór promotie.",
    ],
    confidence: "confirmed",
  },
  {
    id: "v46-build-372-baseline",
    version: "46",
    build: "372",
    releasedAt: "2026-09-19",
    title: "V46-productiebasis vóór centraal ontwikkellogboek",
    newItems: ["Bestaande V46 mobiele productie draaide als build 372."],
    problems: ["Er was nog geen centrale, gebruikersleesbare versiegeschiedenis."],
    causes: ["De zichtbare versieknop was uitsluitend bedoeld om een nieuwere appbuild te controleren."],
    fixes: [],
    now: ["Dit is de laatste bevestigde V46-basis vóór de introductie van het nieuwe logboek in build 373."],
    technicalDetails: ["Bevestigde live V46-buildweergave."],
    confidence: "confirmed",
  },
  {
    id: "v46-github-first-control-plane",
    version: "46",
    build: null,
    releasedAt: "2026-09-19T14:23:27+02:00",
    title: "GitHub-first ontwikkeling en deployment bewezen",
    newItems: ["Normale ontwikkeling, diagnose en deployment kunnen via GitHub zonder dagelijkse Cloud Workstation-koppeling."],
    problems: ["Ontwikkelwerk kon stilvallen wanneer een tijdelijke cloud/workstationverbinding wegviel."],
    causes: ["Dagelijkse ontwikkeling leunde te veel op rechtstreekse cloudtoegang."],
    fixes: ["GitHub Actions, WIF, candidate-checks, rollback en GitHub-only productie-diagnostiek ingericht en end-to-end bewezen."],
    now: ["Normale UI- en backendwijzigingen lopen via GitHub; Workstation is alleen nog break-glass."],
    technicalDetails: ["Bevestigd door GitHub-only deployment proof #154 en post-deploy health proof #155."],
    confidence: "confirmed",
  },
  {
    id: "smart-rescue-20260914",
    version: "46",
    build: null,
    releasedAt: "2026-09-14",
    title: "Smart Rescue DCA ontworpen en geïntegreerd",
    newItems: ["Smart Rescue DCA als aanvullende herstelmodus."],
    problems: ["Verliesposities hadden behoefte aan gecontroleerder herstel dan alleen vaste DCA-stappen."],
    causes: [],
    fixes: ["Herstellogica en bijbehorende instellingen als aparte, optionele module uitgewerkt."],
    now: ["De app kan een slimmere herstelroute aanbieden zonder bestaande modi te vervangen."],
    confidence: "reconstructed",
  },
  {
    id: "profit-lock-ladder-20260911",
    version: "46",
    build: null,
    releasedAt: "2026-09-11",
    title: "Profit Lock Ladder toegevoegd als optionele modus",
    newItems: ["Profit Lock Ladder met eigen aan/uit-keuze."],
    problems: ["Winstbescherming moest kunnen meegroeien zonder bestaande tradingmodi te vervangen."],
    causes: [],
    fixes: ["Nieuwe LONG-only modus ontworpen waarbij SHORT-posities uitsluitend als beschermingslaag dienen."],
    now: ["Gebruikers kunnen winstbescherming activeren zonder de bestaande standaardmodi kwijt te raken."],
    confidence: "reconstructed",
  },
  {
    id: "tradecentrum-20260903",
    version: "46",
    build: null,
    releasedAt: "2026-09-03",
    title: "Tradecentrum uitgebreid met winstsluiting en DCA-inzicht",
    newItems: ["Bulkactie voor winstgevende posities en extra sortering op DCA-activiteit."],
    problems: ["Kleine winsten vrijmaken kostte te veel losse handelingen en actieve posities waren lastiger te prioriteren."],
    causes: [],
    fixes: ["Tradecentrum uitgebreid met compacte winstactie en duidelijkere rangschikking."],
    now: ["Winstgevende posities en veelvuldig bijgezochte posities zijn sneller te herkennen en te beheren."],
    confidence: "reconstructed",
  },
  {
    id: "markets-risk-20260902",
    version: "46",
    build: null,
    releasedAt: "2026-09-02",
    title: "Markets-overzicht en liquidatierisico uitgebreid",
    newItems: ["Markets-overzicht, Bollinger-status en afzonderlijke liquidatierisico-indicatie."],
    problems: ["Marktselectie en liquidatieafstand waren niet snel genoeg in één oogopslag te beoordelen."],
    causes: [],
    fixes: ["Marktinformatie, sortering en risicometers als aparte visuele signalen toegevoegd."],
    now: ["Gebruikers zien marktcontext en liquidatiegevaar sneller naast de tradinginformatie."],
    confidence: "reconstructed",
  },
  {
    id: "manual-markets-20260831",
    version: "46",
    build: null,
    releasedAt: "2026-08-31",
    title: "Handmatige muntkeuze toegevoegd",
    newItems: ["Zelf munten kiezen met LONG/SHORT-richting per markt."],
    problems: ["Automatische selectie bood niet genoeg controle voor gerichte tests en specifieke markten."],
    causes: [],
    fixes: ["Een optionele handmatige marktselectie naast de bestaande automatische selectie toegevoegd."],
    now: ["Gebruikers kunnen specifieke munten en richting kiezen zonder de automatische flow te verwijderen."],
    confidence: "reconstructed",
  },
  {
    id: "android-239-build-207-github-migration",
    version: "2.39",
    build: "207",
    releasedAt: "2026-08-05T19:56:29+02:00",
    title: "Android-project naar GitHub en cloudmigratie gebracht",
    newItems: ["De bestaande TradeMentor Android-code werd als eerste GitHub-snapshot vastgelegd."],
    problems: ["De app bestond al lokaal, maar had nog geen centrale Git-geschiedenis voor de verdere cloudmigratie."],
    causes: ["Ontwikkeling vond vóór deze stap buiten de huidige GitHub-repository plaats."],
    fixes: ["Projectcode, Android-app, serveronderdelen en migratie-instructies in GitHub opgenomen."],
    now: ["Vanaf dit punt is de ontwikkelgeschiedenis rechtstreeks uit Git-commits te reconstrueren."],
    technicalDetails: [
      "Eerste bevestigde Git-commit: d8dae028f79cb831e6f23d209ba220b3f7c253e6.",
      "Snapshot bevatte Android versionName 2.39 en versionCode 207.",
    ],
    confidence: "confirmed",
  },
  {
    id: "local-v162-build80-20260802",
    version: "1.62",
    build: "80",
    releasedAt: "2026-08-02",
    title: "Vroege lokale app groeide naar circa build 80",
    newItems: ["De lokale Android-app was inmiddels uitgegroeid tot een veel bredere tradingapp."],
    problems: [],
    causes: [],
    fixes: [],
    now: ["Deze mijlpaal is uit pre-GitHub projecthistorie gereconstrueerd."],
    confidence: "reconstructed",
  },
  {
    id: "early-v001-20260729",
    version: "001",
    build: null,
    releasedAt: "2026-07-29",
    title: "Eerste werkende TradeMentor-builds",
    newItems: ["Eerste werkende appbouw en vroege releaseplanning."],
    problems: [],
    causes: [],
    fixes: ["Blueprint, projectstatus en changelogstructuur werden gebruikt om de ontwikkeling te ordenen."],
    now: ["Exacte afzonderlijke buildnummers uit deze pre-GitHub fase zijn niet allemaal hard te bewijzen."],
    confidence: "reconstructed",
  },
  {
    id: "project-start-20260728",
    version: "0.1.0-dev",
    build: "1",
    releasedAt: "2026-07-28",
    title: "Start van TradeMentor / Crypto Bot 2026",
    newItems: ["Eerste Android-project en basisarchitectuur opgezet."],
    problems: ["Er bestond nog geen gezamenlijke tradingapp."],
    causes: [],
    fixes: ["De eerste mobiele basis voor scanner, portfolio, strategie- en risicofuncties werd opgezet."],
    now: ["Dit is de oudste gereconstrueerde appmijlpaal in de huidige projecthistorie."],
    confidence: "reconstructed",
  },
];

function releaseTime(value: string) {
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function buildNumber(entry: ReleaseHistoryEntry) {
  const parsed = Number(entry.build);
  return Number.isFinite(parsed) ? parsed : -1;
}

export function getReleaseHistory(): ReleaseHistoryEntry[] {
  const historical = [...HISTORICAL_RELEASES].sort((a, b) => {
    const dateDifference = releaseTime(b.releasedAt) - releaseTime(a.releasedAt);
    return dateDifference || buildNumber(b) - buildNumber(a);
  });
  return [CURRENT_RELEASE, ...historical];
}

export function releaseSearchText(entry: ReleaseHistoryEntry) {
  return [
    entry.version,
    entry.build || "",
    entry.title,
    ...entry.newItems,
    ...entry.problems,
    ...entry.causes,
    ...entry.fixes,
    ...entry.now,
    entry.before || "",
    entry.after || "",
    ...(entry.technicalDetails || []),
  ].join(" ").toLocaleLowerCase("nl-NL");
}
