"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {authenticatedRequest} from "@/lib/cloud-client";

type Account={uid:string;email:string;accountStatus:string;emailVerified:boolean;lastLogin?:string;appVersion:string;environment:string;exchangeConnected:boolean;botEnabled:boolean;monitorEnabled:boolean;strategy:string;phase:string;lastTickAt?:string;lastSyncAt?:string;technicalError:string;health:{status:string;category:string;severity:string;summary:string}};
type Incident={id:string;incidentId:string;uid:string;status:string;severity:string;category:string;summary:string;lastDetectedAt?:string;attempts?:number};
type Audit={id:string;timestamp?:string;actor:string;uid:string;action:string;result:string;incidentId?:string};

export function AdminPortal(){
 const [accounts,setAccounts]=useState<Account[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[audit,setAudit]=useState<Audit[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy("load");setMessage("");try{const [a,i,l]=await Promise.all([authenticatedRequest("/api/admin/health"),authenticatedRequest("/api/admin/incidents"),authenticatedRequest("/api/admin/audit")]);setAccounts(a.accounts||[]);setIncidents(i.incidents||[]);setAudit(l.events||[])}catch(e){setMessage(e instanceof Error?e.message:"Beheerdata kon niet worden geladen.")}finally{setBusy("")}},[]);
 useEffect(()=>{load()},[load]);
 const counts=useMemo(()=>accounts.reduce<Record<string,number>>((out,row)=>(out[row.health?.status]=(out[row.health?.status]||0)+1,out),{}),[accounts]);
 const run=async()=>{setBusy("monitor");try{const r=await authenticatedRequest("/api/admin/health",{method:"POST"});setMessage(`${r.checked} accounts gecontroleerd; ${r.recoveryRequested} veilige herstelacties aangevraagd.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Controle mislukt.")}finally{setBusy("")}};
 const action=async(row:Account,name:string,danger=false)=>{if(danger&&!window.confirm(`Bevestig ${name} voor ${row.email}`))return;setBusy(`${row.uid}:${name}`);try{await authenticatedRequest(`/api/admin/users/${encodeURIComponent(row.uid)}/actions/${name}`,{method:"POST",body:JSON.stringify({confirm:danger,reason:"Handmatige beheeractie vanuit Admin Portal"})});setMessage(`${name} is veilig uitgevoerd voor ${row.email}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Actie mislukt.")}finally{setBusy("")}};
 return <section className="admin-portal"><header className="admin-hero"><div><span>TRADEMENTOR CONTROL PLANE</span><h1>Admin Portal</h1><p>Privacyvriendelijke technische gezondheid, incidenten en begrensd herstel. Geen beheeractie kan orders plaatsen of veiligheidsblokkades omzeilen.</p></div><button onClick={run} disabled={!!busy}>{busy==="monitor"?"Controleren…":"Controleer nu"}</button></header>
 {message&&<p className="admin-message">{message}</p>}
 <div className="admin-metrics"><article><span>Gebruikers</span><strong>{accounts.length}</strong></article><article className="healthy"><span>Gezond</span><strong>{counts.healthy||0}</strong></article><article className="warning"><span>Waarschuwing</span><strong>{counts.warning||0}</strong></article><article className="danger"><span>Actie vereist</span><strong>{counts.action_required||0}</strong></article><article><span>Veilig geblokkeerd</span><strong>{counts.safety_blocked||0}</strong></article></div>
 <section className="admin-panel"><header><div><span>ACCOUNT HEALTH</span><h2>Technische gebruikersstatus</h2></div><small>{busy==="load"?"Laden…":"Alleen noodzakelijke technische metadata"}</small></header><div className="admin-account-list">{accounts.map(row=><article key={row.uid}><div className="admin-account-head"><div><strong>{row.email||"E-mail niet beschikbaar"}</strong><small>{row.environment} · {row.appVersion} · {row.accountStatus}</small></div><span className={`health ${row.health.status}`}>{row.health.status.replaceAll("_"," ")}</span></div><div className="admin-account-grid"><span><i>Botfase</i><b>{row.phase}</b></span><span><i>Laatste tick</i><b>{row.lastTickAt?new Date(row.lastTickAt).toLocaleString("nl-NL"):"—"}</b></span><span><i>Exchange</i><b>{row.exchangeConnected?"Verbonden":"Niet bewezen"}</b></span><span><i>Diagnose</i><b>{row.health.summary}</b></span></div><div className="admin-actions"><button onClick={()=>action(row,"check")}>Controle</button><button onClick={()=>action(row,"reconcile")}>Reconciliatie</button><button onClick={()=>action(row,"restart_monitor")}>Monitoring herstarten</button><button onClick={()=>action(row,"verify_email")}>Verificatiemail</button><button onClick={()=>action(row,"password_reset")}>Resetmail</button><button className="danger" onClick={()=>action(row,row.accountStatus==="blocked"?"unblock":"block",true)}>{row.accountStatus==="blocked"?"Deblokkeren":"Blokkeren"}</button></div></article>)}</div></section>
 <div className="admin-columns"><section className="admin-panel"><header><div><span>INCIDENTEN</span><h2>Actieve signalen</h2></div></header>{incidents.slice(0,20).map(item=><article className="admin-event" key={item.id}><span className={`severity ${item.severity}`}>{item.severity}</span><div><strong>{item.summary}</strong><small>{item.category} · {item.status} · {item.attempts||0} herstelpogingen</small></div></article>)}</section><section className="admin-panel"><header><div><span>AUDITLOG</span><h2>Onveranderbare acties</h2></div></header>{audit.slice(0,20).map(item=><article className="admin-event" key={item.id}><span>{item.timestamp?new Date(item.timestamp).toLocaleTimeString("nl-NL"):"—"}</span><div><strong>{item.action}</strong><small>{item.actor} · {item.result}</small></div></article>)}</section></div>
 </section>
}
