"use client";

import { useState } from "react";
import { parseAsterBotStatus, type StrategyDashboardStatus } from "@/lib/aster-bot-status";

const runtimeLabel: Record<string,string>={LIVE:"ACTIEF",PAPER:"PAPER",STOPPED:"UIT",BLOCKED:"GEBLOKKEERD",RECOVERING:"HERSTEL",UNKNOWN:"ONBEKEND"};
const entryLabel: Record<string,string>={ALLOWED:"AANVULLEN ACTIEF",WAITING:"AANVULLEN WACHT",BLOCKED:"AANVULLEN GEBLOKKEERD",UNKNOWN:"INSTAPSTATUS ONBEKEND"};
function time(value:unknown){const date=new Date(String(value||""));return Number.isFinite(date.getTime())?date.toLocaleString("nl-NL",{dateStyle:"short",timeStyle:"medium"}):"Niet bewezen"}
function StrategyDetail({value}:{value:StrategyDashboardStatus}){return <section className="bot-strategy-detail" aria-label="Strategy 2 details"><dl><div><dt>Modus</dt><dd>{value.mode}</dd></div><div><dt>Fase</dt><dd>{value.phase}</dd></div><div><dt>Scheduler</dt><dd>{value.schedulerStatus.status}</dd></div><div><dt>Eigen posities</dt><dd>{value.ownedPositions}</dd></div><div><dt>Laatste controle</dt><dd>{time(value.lastTickAt)}</dd></div></dl><p><b>Laatste bewezen actie</b>{value.lastAction==="NIET_BEWEZEN"?"Niet bewezen":value.lastAction}</p><p><b>Laatste reden</b>{value.lastReason}</p></section>}
export function AsterBotStatus({snapshot}:{snapshot:Record<string,unknown>|null}){const [open,setOpen]=useState(false);const value=parseAsterBotStatus(snapshot);if(!value)return <div className="aster-bot-status unreliable"><header><span>BOTSTATUS</span><strong>STATUS NIET BETROUWBAAR</strong></header><p>Wacht op actuele Strategy-2 gegevens van Aster.</p></div>;const entryTone=value.newEntry.status.toLowerCase();return <div className={`aster-bot-status ${value.dataFresh?"":"unreliable"}`}><header><span>BOTSTATUS · ALLEEN STRATEGY 2</span><small>{value.dataFresh?`Bijgewerkt ${time(value.evaluatedAt)}`:"STATUS NIET BETROUWBAAR"}</small></header><div className="bot-strategies"><button type="button" className={`bot-strategy ${value.strategy2.status.toLowerCase()}`} aria-expanded={open} onClick={()=>setOpen(!open)}><span>STRATEGY 2</span><strong>{runtimeLabel[value.strategy2.status]||"ONBEKEND"}</strong><em>{value.strategy2.status==="LIVE"?"LIVE":value.strategy2.mode}</em><small>{value.strategy2.ownedPositions} posities beheerd</small><i>{open?"−":"+"}</i></button></div>{open&&<StrategyDetail value={value.strategy2}/>}<div className="bot-account-line"><div><span>ACCOUNTPOSITIES</span><strong>{value.account.activePositions}</strong></div><div><span>STRATEGY 2 · BEHEERD / DOEL</span><strong>{value.strategy2.ownedPositions} / {value.targetPositions}</strong></div><div><span>NOG TE VULLEN</span><strong>{value.remainingToTarget}</strong></div></div><p className="bot-direction-line"><b>{value.account.longPositions} LONG</b><i/><b>{value.account.shortPositions} SHORT</b><span>{value.account.openOrders} open orders</span></p><div className={`bot-entry-status ${entryTone}`}><strong>{entryLabel[value.newEntry.status]}</strong><span>{value.newEntry.reasonText}</span></div><div className="bot-last-proof"><span>Laatste Strategy-2-controle: <b>{time(value.strategy2.lastTickAt)}</b></span><span>Laatste Strategy-2-actie: <b>{value.strategy2.lastAction==="NIET_BEWEZEN"?"Niet bewezen":value.strategy2.lastAction}</b></span></div></div>}
