"use client";
import { useEffect, useState } from "react";
import { authenticatedRequest } from "@/lib/cloud-client";

type Draft={name:string;base:string;tp:string;positions:string;universe:string;leverage:string;budget:string;longDca:string;shortDca:string;longMax:string;shortMax:string;protection:boolean;trailing:boolean;activation:string;distance:string;minimum:string};
const defaults:Draft={name:"Dual Harvest Adaptive Shield",base:"10",tp:"1.5",positions:"20",universe:"100",leverage:"20",budget:"35",longDca:"2",shortDca:"2",longMax:"5",shortMax:"5",protection:true,trailing:false,activation:"1.5",distance:"0.5",minimum:"0.3"};
const n=(v:unknown,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d};
function fromState(s:Record<string,unknown>):Draft{return{name:String(s.name||defaults.name),base:String(s.baseNotional??10),tp:String(n(s.takeProfit,.015)*100),positions:String(s.maximumPositions??20),universe:String(s.universeTopN??100),leverage:String(s.leverage??20),budget:String(n(s.strategyBudget,.35)*100),longDca:String(n(s.longDcaDistance,.02)*100),shortDca:String(n(s.shortDcaDistance,.02)*100),longMax:String(s.longMaxDca??5),shortMax:String(s.shortMaxDca??5),protection:s.protectionEnabled!==false,trailing:s.trailingEnabled===true,activation:String(n(s.trailingActivation,.015)*100),distance:String(n(s.trailingDistance,.005)*100),minimum:String(n(s.trailingMinNetProfit,.003)*100)}}

export function AsterStrategy3Control({snapshot,onChanged}:{snapshot:Record<string,unknown>|null;onChanged:()=>void}){
 const state=(snapshot?.strategy3&&typeof snapshot.strategy3==="object"?snapshot.strategy3:{}) as Record<string,unknown>;
 const settings=(state.settings&&typeof state.settings==="object"?state.settings:{}) as Record<string,unknown>;
 const [draft,setDraft]=useState<Draft>(()=>fromState(settings));const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [readiness,setReadiness]=useState<Record<string,unknown>|null>(null);const [confirmCanary,setConfirmCanary]=useState(false);
 useEffect(()=>{if(open)return;setDraft(fromState(settings))},[snapshot,open]);
 const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(old=>({...old,[key]:value}));
 const payload=()=>({strategyId:"aster-strategy-3",name:draft.name,mode:"paper",baseNotional:n(draft.base),takeProfit:n(draft.tp)/100,autoRestart:true,dcaEnabled:true,longDcaDistance:n(draft.longDca)/100,shortDcaDistance:n(draft.shortDca)/100,longMaxDca:Math.round(n(draft.longMax)),shortMaxDca:Math.round(n(draft.shortMax)),dcaMultiplier:1,maximumPositions:Math.round(n(draft.positions)),universeTopN:Math.round(n(draft.universe)),leverage:Math.round(n(draft.leverage)),marginMode:"cross",strategyBudget:n(draft.budget)/100,protectionEnabled:draft.protection,trailingEnabled:draft.trailing,trailingActivation:n(draft.activation)/100,trailingDistance:n(draft.distance)/100,trailingMinNetProfit:n(draft.minimum)/100});
 async function run(kind:"save"|"simulate"){setBusy(true);setMessage("");try{const value=payload();const result=await authenticatedRequest(`/api/exchanges/aster/strategy3/${kind==="save"?"settings":"simulate"}`,{method:kind==="save"?"PUT":"POST",body:JSON.stringify({settings:value})}) as Record<string,unknown>;if(kind==="save"){const strategy3=(result.strategy3&&typeof result.strategy3==="object"?result.strategy3:{}) as Record<string,unknown>;const saved=(strategy3.settings&&typeof strategy3.settings==="object"?strategy3.settings:{}) as Record<string,unknown>;const savedBase=n(saved.baseNotional,Number.NaN);const savedTrailing=saved.trailingEnabled===true;if(!Number.isFinite(savedBase)||Math.abs(savedBase-value.baseNotional)>.000001||savedTrailing!==value.trailingEnabled)throw new Error("De server bevestigde niet dezelfde Strategy-3-instellingen. Er is niets als succesvol gepresenteerd; probeer opnieuw.");setDraft(fromState(saved));setMessage(`Strategy 3 is server-side bevestigd: basisorder US$ ${savedBase.toFixed(2)} en trailing ${savedTrailing?"aan":"uit"}. Nieuwe orders gebruiken deze liveconfiguratie; bestaande posities blijven ongewijzigd.`);await Promise.resolve(onChanged())}else setMessage(String(result.message||"Paper-simulatie afgerond."))}catch(e){setMessage(e instanceof Error?e.message:"Actie mislukt")}finally{setBusy(false)}}
 async function checkReadiness(){setBusy(true);setMessage("");try{const result=await authenticatedRequest("/api/exchanges/aster/strategy3/readiness") as Record<string,unknown>;setReadiness(result);setMessage(result.liveReady?"Strategy 3 is volledig live-gereed.":result.softwareReady?"Technische controles geslaagd. Bevestig nu afzonderlijk de mini-canary.":"Nog niet alle technische controles zijn geslaagd.");await Promise.resolve(onChanged())}catch(e){setMessage(e instanceof Error?e.message:"Gereedheidscontrole mislukt")}finally{setBusy(false)}}
 async function canary(){if(!confirmCanary){setMessage("Vink eerst de echte canary-toestemming aan.");return}setBusy(true);setMessage("Canary wordt één keer uitgevoerd; bij onzekere status volgt geen automatische retry.");try{const result=await authenticatedRequest("/api/exchanges/aster/strategy3/canary",{method:"POST",body:JSON.stringify({confirm:true,notional_usd:10})}) as Record<string,unknown>;setMessage(String(result.message||"Canary afgerond."));setConfirmCanary(false);await checkReadiness();await Promise.resolve(onChanged())}catch(e){setMessage(e instanceof Error?e.message:"Canary veilig gestopt");setBusy(false)}}
 async function toggleLive(){setBusy(true);setMessage("");try{const enabled=state.enabled===true;const result=await authenticatedRequest(`/api/exchanges/aster/strategy3/${enabled?"stop":"start"}`,{method:"POST",body:JSON.stringify(enabled?{confirm:true}:{confirm:true,settings:payload()})}) as Record<string,unknown>;setMessage(enabled?"Strategy 3 is veilig gestopt; monitoring blijft actief.":String(result.started?"Strategy 3 live is gestart.":"Start niet bevestigd."));await Promise.resolve(onChanged())}catch(e){setMessage(e instanceof Error?e.message:"Live-actie mislukt")}finally{setBusy(false)}}
 const checks=Array.isArray(readiness?.checks)?readiness.checks as Record<string,unknown>[]:[];const liveReady=state.liveReady===true;
 return <article className="strategy-card strategy-three-card"><div className="strategy-title-row"><div><span className="kicker">STRATEGY 3 · NIEUW</span><h2>Dual Harvest Adaptive Shield</h2></div><span className={`strategy-state ${state.enabled?"on":""}`}>{state.enabled?"LIVE":liveReady?"LIVE READY":"SIMULATIE"}</span></div><p>LONG en SHORT oogsten zelfstandig winst. Bij verhoogd risico kan iedere kant tijdelijk de andere beschermen. Bescherming staat boven vaste TP en trailing.</p><div className="strategy-facts"><span>{String(state.activeTrades||0)} trades</span><span>{String(state.longLegs||0)} LONG · {String(state.shortLegs||0)} SHORT</span><span>{String(state.harvestLegs||0)} harvest · {String(state.shieldLegs||0)} shield</span><span>{liveReady?"LIVE READY":"LIVE GEBLOKKEERD"}</span></div><div className="strategy-message">{String(state.lastReason||"Nieuw — simulatie; standaard uit")}</div><div className="strategy3-priority"><b>Beslisvolgorde</b><span>Exchange-truth → noodrisico → Shield → veilige winstname → trailing → DCA → nieuwe kans</span></div><div className={`strategy-power-control ${state.enabled?"enabled":liveReady?"ready":"locked"}`}><span><b>Strategy 3 live bot</b><small>{state.enabled?"AAN · bot draait":liveReady?"UIT · canary en controles geslaagd":"UIT · veiligheidscontrole nodig"}</small></span><button type="button" role="switch" aria-checked={Boolean(state.enabled)} disabled={busy||(!liveReady&&state.enabled!==true)} onClick={toggleLive}><i />{state.enabled?"Uitschakelen":"Inschakelen"}</button></div><button className="expand-settings" type="button" onClick={()=>setOpen(x=>!x)}>{open?"Instellingen sluiten":"Strategy 3 instellen"}</button><button className="expand-settings" disabled={busy} onClick={checkReadiness}>Controleer live-gereedheid</button>{Boolean(readiness?.softwareReady)&&!Boolean(readiness?.liveReady)&&<div className="canary-confirm"><label><input type="checkbox" checked={confirmCanary} onChange={e=>setConfirmCanary(e.target.checked)}/><span>Ik geef toestemming voor één echte Aster-canary van maximaal US$ 10 die direct na de bevestigde fill wordt gesloten. Fees en koersafwijking zijn mogelijk.</span></label><button className="stop-action" disabled={busy||!confirmCanary} onClick={canary}>Voer Strategy-3-canary uit</button></div>}{checks.length>0&&<div className="readiness-list">{checks.map(x=><div key={String(x.key)} className={x.passed?"ready":"blocked"}><b>{x.passed?"✓":"!"}</b><span>{String(x.message||x.key)}</span></div>)}</div>}{open&&<Editor draft={draft} set={set} busy={busy} run={run}/>} {message&&<p className="strategy-message">{message}</p>}</article>
}
function Editor({draft,set,busy,run}:{draft:Draft;set:<K extends keyof Draft>(key:K,value:Draft[K])=>void;busy:boolean;run:(kind:"save"|"simulate")=>void}){return <div className="strategy-inline-editor"><Edit label="Naam" value={draft.name} set={x=>set("name",x)}/><Edit label="Basisorder (US$ exposure)" value={draft.base} set={x=>set("base",x)}/><Edit label="Take Profit (%)" value={draft.tp} set={x=>set("tp",x)}/><Edit label="Maximaal actieve posities" value={draft.positions} set={x=>set("positions",x)}/><Choice label="Coin-universe" value={draft.universe} values={["50","100","200"]} set={x=>set("universe",x)}/><Edit label="Leverage" value={draft.leverage} set={x=>set("leverage",x)}/><Edit label="Strategy Budget (%)" value={draft.budget} set={x=>set("budget",x)}/><Edit label="LONG DCA-afstand (%)" value={draft.longDca} set={x=>set("longDca",x)}/><Edit label="SHORT DCA-afstand (%)" value={draft.shortDca} set={x=>set("shortDca",x)}/><Edit label="Max LONG DCA" value={draft.longMax} set={x=>set("longMax",x)}/><Edit label="Max SHORT DCA" value={draft.shortMax} set={x=>set("shortMax",x)}/><Toggle label="Adaptive Shield" checked={draft.protection} set={x=>set("protection",x)}/><Toggle label="Protected Trailing Harvest" checked={draft.trailing} set={x=>set("trailing",x)}/>{draft.trailing&&<><Edit label="Trailing activeren vanaf (%)" value={draft.activation} set={x=>set("activation",x)}/><Edit label="Vaste trailing-afstand (%)" value={draft.distance} set={x=>set("distance",x)}/><Edit label="Minimale netto winst (%)" value={draft.minimum} set={x=>set("minimum",x)}/></>}<div className="inline-editor-footer"><p>Opslaan en simuleren verzenden nooit een Aster-order.</p><button disabled={busy} onClick={()=>run("save")}>Opslaan</button><button disabled={busy} onClick={()=>run("simulate")}>Simuleer scenario&apos;s</button></div></div>}
function Edit({label,value,set}:{label:string;value:string;set:(x:string)=>void}){return <label><span>{label}</span><input value={value} onChange={e=>set(e.target.value)}/></label>}
function Choice({label,value,values,set}:{label:string;value:string;values:string[];set:(x:string)=>void}){return <label><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{values.map(x=><option key={x}>{x}</option>)}</select></label>}
function Toggle({label,checked,set}:{label:string;checked:boolean;set:(x:boolean)=>void}){return <label className="strategy-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/></label>}
