"use client";
import { useEffect, useMemo, useState } from "react";
import type { ExchangeSnapshot } from "@/lib/use-exchange-data";
import { runBacktest, type BacktestCandle, type BacktestResult, type BacktestSettings } from "@/lib/backtest-engine";

type Variant = "A" | "B";
const defaults: BacktestSettings = { startingPortfolio:1000, baseNotional:20, leverage:20, takeProfitPct:1.5, dcaDistancePct:2, maxDca:5, feePct:0.05, slippagePct:0.03 };
const num=(v:unknown,fallback:number)=>Number.isFinite(Number(v))?Number(v):fallback;
const usd=(v:number)=>`US$ ${v.toLocaleString("nl-NL",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function settingsFrom(snapshot: ExchangeSnapshot): BacktestSettings { const root=snapshot.data||{}; const s2=root.strategy2&&typeof root.strategy2==="object"?root.strategy2 as Record<string,unknown>:{}; const s=s2.settings&&typeof s2.settings==="object"?s2.settings as Record<string,unknown>:{}; return {...defaults,startingPortfolio:num(root.portfolioValue??root.equity,1000),baseNotional:num(s.baseNotional,20),leverage:num(s.leverage,20),takeProfitPct:num(s.takeProfit,0.015)*100,dcaDistancePct:num(s.longDcaDistance,0.02)*100,maxDca:num(s.longMaxDca,5)}; }

export function BacktestComparison({snapshot}:{snapshot:ExchangeSnapshot}){
  const live=useMemo(()=>settingsFrom(snapshot),[snapshot]);
  const [settings,setSettings]=useState<Record<Variant,BacktestSettings>>({A:live,B:live}); const [results,setResults]=useState<Partial<Record<Variant,BacktestResult>>>({}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{for(const key of ["A","B"] as const){const saved=localStorage.getItem(`tradementor.backtest.${key}.settings`);if(saved)try{setSettings(current=>({...current,[key]:{...live,...JSON.parse(saved)}}))}catch{}}},[]); // initial independent copies
  const change=(variant:Variant,key:keyof BacktestSettings,value:number)=>setSettings(current=>{const next={...current,[variant]:{...current[variant],[key]:value}};localStorage.setItem(`tradementor.backtest.${variant}.settings`,JSON.stringify(next[variant]));return next});
  const run=async()=>{setBusy(true);setMessage("Dezelfde historische candles worden voor A en B geladen…");try{const response=await fetch("/api/market-data?exchange=aster&symbol=BTCUSDT&interval=15m&limit=1000");const payload=await response.json();if(!response.ok||!Array.isArray(payload.candles))throw new Error(payload.error||"Historische candles ontbreken.");const candles=payload.candles as BacktestCandle[];const A=runBacktest(candles,settings.A),B=runBacktest(candles,settings.B);setResults({A,B});setMessage(A.valid&&B.valid?`Rekencontrole geslaagd · ${candles.length} identieke candles · geen echte orders`:`Backtest ongeldig: accountingcontrole is mislukt.`);localStorage.setItem("tradementor.backtest.lastRun",JSON.stringify({at:new Date().toISOString(),symbol:"BTCUSDT",timeframe:"15m",A,B}));}catch(e){setMessage(e instanceof Error?e.message:"Backtest kon niet worden uitgevoerd.")}finally{setBusy(false)}};
  return <section className="backtest-workspace"><header><div><span className="kicker">STRATEGY 2 · VEILIGE SIMULATIE</span><h2>Live vergelijken met twee backtests</h2><p>A en B gebruiken dezelfde historische marktdata, maar volledig onafhankelijke instellingen en virtuele rekeningen.</p></div><button onClick={run} disabled={busy}>{busy?"Berekenen…":"Start beide backtests"}</button></header><div className="backtest-safety">SIMULATIE · echte orderuitvoering is technisch niet beschikbaar in deze omgeving</div><div className="backtest-columns"><LiveCard snapshot={snapshot} settings={live}/>{(["A","B"] as const).map(v=><TestCard key={v} variant={v} settings={settings[v]} result={results[v]} liveEquity={live.startingPortfolio} change={change} reset={()=>setSettings(c=>({...c,[v]:live}))}/>)}</div>{message&&<p className="backtest-message">{message}</p>}</section>;
}
function LiveCard({snapshot,settings}:{snapshot:ExchangeSnapshot;settings:BacktestSettings}){const d=snapshot.data||{};return <article className="backtest-card live"><span>LIVE · ALLEEN LEZEN</span><h3>Werkelijke Strategy 2</h3><Metric label="Portfolio" value={usd(num(d.portfolioValue??d.equity,0))}/><Metric label="Open PnL" value={usd(num(d.openPnl??d.unrealizedPnl,0))}/><Metric label="Actieve trades" value={String(num(d.activePositions??d.positionCount,0))}/><small>Basis {usd(settings.baseNotional)} · TP {settings.takeProfitPct.toFixed(2)}% · {settings.leverage}×</small></article>}
function TestCard({variant,settings,result,liveEquity,change,reset}:{variant:Variant;settings:BacktestSettings;result?:BacktestResult;liveEquity:number;change:(v:Variant,k:keyof BacktestSettings,n:number)=>void;reset:()=>void}){const delta=result?result.endingPortfolio-liveEquity:0;return <article className="backtest-card"><span>BACKTEST {variant} · FICTIEF</span><h3>Virtueel account {variant}</h3><div className="backtest-inputs"><Field label="Startportfolio" value={settings.startingPortfolio} set={n=>change(variant,"startingPortfolio",n)}/><Field label="Basisorder" value={settings.baseNotional} set={n=>change(variant,"baseNotional",n)}/><Field label="TP %" value={settings.takeProfitPct} set={n=>change(variant,"takeProfitPct",n)}/><Field label="DCA %" value={settings.dcaDistancePct} set={n=>change(variant,"dcaDistancePct",n)}/><Field label="Max DCA" value={settings.maxDca} set={n=>change(variant,"maxDca",n)}/><Field label="Leverage" value={settings.leverage} set={n=>change(variant,"leverage",n)}/></div><button className="backtest-reset" onClick={reset}>Reset naar Live</button>{result&&<div className="backtest-results"><Metric label="Eindportfolio" value={usd(result.endingPortfolio)}/><Metric label="Netto PnL" value={usd(result.netPnl)}/><Metric label="Rendement" value={`${result.returnPct.toFixed(2)}%`}/><Metric label="Verschil met Live" value={`${delta>=0?"+":""}${usd(delta)}`}/><Metric label="Max drawdown" value={`${result.maxDrawdownPct.toFixed(2)}%`}/><Metric label="Winrate" value={`${result.winRatePct.toFixed(1)}%`}/><Metric label="Gesloten trades" value={String(result.closedTrades)}/><Metric label="DCA-orders" value={String(result.dcaOrders)}/><Metric label="Fees" value={usd(result.fees)}/><Metric label="Profit factor" value={result.profitFactor?.toFixed(2)??"—"}/><small>{result.valid?"✓ Accounting-invariants geslaagd":"! Resultaat ongeldig"}</small></div>}</article>}
function Metric({label,value}:{label:string;value:string}){return <div className="backtest-metric"><small>{label}</small><strong>{value}</strong></div>}
function Field({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <label><span>{label}</span><input type="number" min="0" step="0.01" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
