"use client";

import { useCallback, useEffect, useState } from "react";
import { authenticatedRequest } from "@/lib/cloud-client";

type Growth = { setupRequired?:boolean; reliable?:boolean; closeEnabled?:boolean; baseline?:number;
  expectedEndValue?:number; difference?:number; percentage?:number; positionCount?:number; blockReason?:string; quoteId?:string; };
const money=(value:number,signed=false)=>`${value<0?"-":signed?"+":""}US$ ${Math.abs(value).toLocaleString("nl-NL",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const percent=(value:number)=>`${value>=0?"+":""}${value.toLocaleString("nl-NL",{minimumFractionDigits:2,maximumFractionDigits:2})}%`;

export function PortfolioGrowthCard({onChanged=()=>{}}:{onChanged?:()=>void}) {
  const [data,setData]=useState<Growth|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [amount,setAmount]=useState(""),[confirm,setConfirm]=useState(false),[reset,setReset]=useState(false),[resetReason,setResetReason]=useState("");
  const load=useCallback(async()=>{setError("");try{setData(await authenticatedRequest("/api/exchanges/aster/portfolio-growth") as Growth)}catch(e){setData({reliable:false});setError(e instanceof Error?e.message:"Berekening niet beschikbaar")}},[]);
  useEffect(()=>{let active=true;authenticatedRequest("/api/exchanges/aster/portfolio-growth").then(value=>{if(active)setData(value as Growth)}).catch(cause=>{if(active){setData({reliable:false});setError(cause instanceof Error?cause.message:"Berekening niet beschikbaar")}});return()=>{active=false}},[]);
  async function saveBaseline(isReset=false){const value=Number(amount.replace(",","."));if(!Number.isFinite(value)||value<=0){setError("Vul een geldige positieve startwaarde in.");return}setBusy(true);setError("");try{const path=isReset?"/api/exchanges/aster/portfolio-growth/reset":"/api/exchanges/aster/portfolio-growth";const body=isReset?{amount:value,currency:"USD",confirm:true,reason:resetReason}:{amount:value,currency:"USD",confirm:true};setData(await authenticatedRequest(path,{method:"POST",body:JSON.stringify(body)}) as Growth);setConfirm(false);setReset(false);setAmount("");setResetReason("");onChanged()}catch(e){setError(e instanceof Error?e.message:"Startwaarde opslaan is mislukt.")}finally{setBusy(false)}}
  async function closeAll(){if(!data?.quoteId)return;setBusy(true);setError("");try{const result=await authenticatedRequest("/api/exchanges/aster/automation/close-all",{method:"POST",body:JSON.stringify({confirm:true,quote_id:data.quoteId,idempotency_key:crypto.randomUUID()})}) as Record<string,unknown>;setConfirm(false);await load();onChanged();setError(String(result.message??"Alles is bevestigd gesloten; account blijft gepauzeerd."))}catch(e){setError(e instanceof Error?e.message:"Alles sluiten is fail-closed gestopt.")}finally{setBusy(false)}}
  const difference=Number(data?.difference??0),tone=!data?.reliable?"unreliable":difference>0?"profit":difference<0?"loss":"neutral";
  return <><article className={`metric portfolio-growth ${tone}`} aria-live="polite"><span>PORTFOLIO GROEI</span>{data?.setupRequired?<div className="portfolio-growth-setup"><small>Stel eenmalig je startwaarde in</small><input aria-label="Startwaarde in US-dollar" inputMode="decimal" placeholder="US$ 359,00" value={amount} onChange={e=>setAmount(e.target.value)} /><button disabled={busy} onClick={()=>setConfirm(true)}>STARTWAARDE OPSLAAN</button></div>:<><small>Netto winst bij alles sluiten</small><strong className="portfolio-growth-money">{data?.reliable?money(difference,true):"—"}</strong><b>{data?.reliable?percent(Number(data?.percentage??0)):"Onbetrouwbaar"}</b><button className="portfolio-close-all" disabled={busy||!data?.closeEnabled} onClick={()=>setConfirm(true)}>ALLES SLUITEN</button><small>Startwaarde {data?.baseline?money(data.baseline):"—"}</small><button className="portfolio-baseline-reset" disabled={busy} onClick={()=>setReset(true)}>Startwaarde resetten</button></>}{error&&<em>{error}</em>}{!error&&!data?.reliable&&!data?.setupRequired&&<em>{data?.blockReason||"Sluiten is veilig geblokkeerd"}</em>}</article>
  {confirm&&<div className="portfolio-growth-modal" role="presentation" onMouseDown={()=>setConfirm(false)}><section role="dialog" aria-modal="true" aria-label={data?.setupRequired?"Startwaarde bevestigen":"Alles sluiten bevestigen"} onMouseDown={e=>e.stopPropagation()}>{data?.setupRequired?<><h3>Startwaarde bevestigen</h3><p>Deze persoonlijke startwaarde wordt server-side opgeslagen en kan daarna alleen via de resetprocedure worden gewijzigd.</p><dl><dt>Startwaarde</dt><dd>{money(Number(amount.replace(",","."))||0)}</dd><dt>Valuta</dt><dd>USD</dd></dl></>:<><h3>Alles sluiten bevestigen</h3><dl><dt>Actuele startwaarde</dt><dd>{money(Number(data?.baseline??0))}</dd><dt>Verwachte netto eindwaarde</dt><dd>{money(Number(data?.expectedEndValue??0))}</dd><dt>Verwacht verschil</dt><dd>{money(difference,true)}</dd><dt>Verwacht percentage</dt><dd>{percent(Number(data?.percentage??0))}</dd><dt>Posities</dt><dd>{data?.positionCount??0}</dd></dl><p>De server haalt alles opnieuw op en gaat alleen door als de nettowinst nog betrouwbaar positief is. De bot blijft daarna gepauzeerd.</p></>}<footer><button disabled={busy} onClick={()=>setConfirm(false)}>Annuleren</button><button disabled={busy} onClick={()=>data?.setupRequired?saveBaseline(false):closeAll()}>{data?.setupRequired?"Bevestig startwaarde":"Bevestig alles sluiten"}</button></footer></section></div>}
  {reset&&<div className="portfolio-growth-modal" role="presentation" onMouseDown={()=>setReset(false)}><section role="dialog" aria-modal="true" aria-label="Startwaarde resetten" onMouseDown={e=>e.stopPropagation()}><h3>Startwaarde handmatig resetten</h3><p>Deze wijziging wordt met oude waarde, nieuwe waarde, reden en account-ID geaudit.</p><label>Nieuwe startwaarde<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} /></label><label>Reden<textarea value={resetReason} onChange={e=>setResetReason(e.target.value)} /></label><footer><button onClick={()=>setReset(false)}>Annuleren</button><button disabled={busy||resetReason.trim().length<10} onClick={()=>saveBaseline(true)}>Reset bevestigen</button></footer></section></div>}</>;
}
