const BASE_ITEMS=window.BASE_ITEMS; const BASE_PACKAGES=window.BASE_PACKAGES;
const clone=x=>JSON.parse(JSON.stringify(x));
let items=JSON.parse(localStorage.getItem('ob_items')||'null')||clone(BASE_ITEMS); let packages=JSON.parse(localStorage.getItem('ob_packages')||'null')||clone(BASE_PACKAGES); let order=[]; let currentTab='articles';
const save=()=>{localStorage.setItem('ob_items',JSON.stringify(items));localStorage.setItem('ob_packages',JSON.stringify(packages));};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function init(){renderPacks();fillCats();renderArticles();renderOrder();['search','category','status'].forEach(id=>document.getElementById(id).addEventListener(id==='search'?'input':'change',renderArticles));}
function fillCats(){let s=document.getElementById('category'),old=s.value; s.innerHTML='<option value="">Alle categorieën</option>'+[...new Set(items.map(x=>x.category).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('');s.value=old}
function renderPacks(){document.getElementById('packs').innerHTML=packages.map((p,i)=>`<button class="pack" onclick="addPackage(${i})">${esc(p.name)}</button>`).join('')}
function filtered(){let q=document.getElementById('search').value.toLowerCase().trim(),c=document.getElementById('category').value,st=document.getElementById('status').value;return items.filter(x=>(!q||(x.code+' '+x.description).toLowerCase().includes(q))&&(!c||x.category===c)&&(!st||x.status===st));}
function renderArticles(){let a=filtered();document.getElementById('count').textContent=`${a.length} van ${items.length}`;document.getElementById('articles').innerHTML=a.map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.description||'—')}</td><td>${esc(x.category||'Overig')}</td><td><span class="badge ${x.status.toLowerCase().startsWith('ref')?'ref':'new'}">${esc(x.status)}</span></td><td><button class="add" onclick='addItem(${JSON.stringify(x.code)},${JSON.stringify(x.status)})'>+ Toevoegen</button></td></tr>`).join('')}
function findItem(code,status){return items.find(x=>x.code===code&&x.status===status)||items.find(x=>x.code===code)||{code,description:'Omschrijving nog invullen',status,category:'Pakketartikel'}}
function addItem(code,status,qty=1){let x=findItem(code,status),o=order.find(y=>y.code===code&&y.status===status); if(o)o.qty+=qty;else order.push({...x,qty});renderOrder();}
function addPackage(i){packages[i].items.forEach(x=>addItem(x.code,x.status,x.qty||1));toast(packages[i].name+' toegevoegd')}
function renderOrder(){let body=document.getElementById('order'),empty=document.getElementById('empty');empty.style.display=order.length?'none':'block';body.innerHTML=order.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.code)}</b><br><span style="font-size:10px;color:#62748a">${esc(x.status)}</span></td><td>${esc(x.description||'—')}</td><td><span class="qty"><button onclick="chg(${i},-1)">−</button><span>${x.qty}</span><button onclick="chg(${i},1)">+</button></span></td><td><button class="trash" onclick="del(${i})">⌫</button></td></tr>`).join('');document.getElementById('lines').textContent=order.length;document.getElementById('pieces').textContent=order.reduce((a,b)=>a+b.qty,0)}
function chg(i,d){order[i].qty+=d;if(order[i].qty<=0)order.splice(i,1);renderOrder()} function del(i){order.splice(i,1);renderOrder()} function clearOrder(){order=[];renderOrder()}
async function copyDynamics(){if(!order.length)return toast('Selecteer eerst artikelen'); let rows=[];order.forEach(x=>{for(let i=0;i<x.qty;i++)rows.push(`${x.code}\t${x.status}`)});let text=rows.join('\n');try{await navigator.clipboard.writeText(text);toast(`${rows.length} regels gekopieerd voor Dynamics`)}catch(e){let t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();toast(`${rows.length} regels gekopieerd`)}}
function openAdmin(tab){document.getElementById('admin').classList.add('show');adminTab(tab||'articles')} function closeAdmin(){document.getElementById('admin').classList.remove('show')}
function adminTab(t){currentTab=t;document.getElementById('ta').classList.toggle('on',t==='articles');document.getElementById('tp').classList.toggle('on',t==='packages');renderAdmin()}
function renderAdmin(){let c=document.getElementById('adminContent'); if(currentTab==='articles'){c.innerHTML=`<div class="gridform"><input id="acode" class="mini" placeholder="Artikelnummer"><input id="adesc" class="mini" placeholder="Omschrijving"><select id="astatus" class="mini"><option>Nieuw</option><option>Refurb</option></select><input id="acat" class="mini" placeholder="Categorie"><button class="save" onclick="newArticle()">+ Toevoegen</button></div><div><div class="adminrow" style="font-weight:800;background:#f5f8fb"><div>Artikel</div><div>Omschrijving</div><div>Status</div><div>Categorie</div><div></div></div>${items.map((x,i)=>`<div class="adminrow"><div>${esc(x.code)}</div><div>${esc(x.description)}</div><div>${esc(x.status)}</div><div>${esc(x.category)}</div><div><button class="smallbtn" style="color:#d92d20" onclick="removeArticle(${i})">Verwijder</button></div></div>`).join('')}</div>`} else {c.innerHTML=`<div class="gridform" style="grid-template-columns:1fr auto"><input id="pname" class="mini" placeholder="Naam nieuw pakket"><button class="save" onclick="newPackage()">+ Pakket</button></div>${packages.map((p,i)=>`<div style="border:1px solid #dbe4ef;border-radius:9px;margin:9px 0;padding:11px"><div style="display:flex;justify-content:space-between;align-items:center"><b>${esc(p.name)}</b><button class="smallbtn" style="color:#d92d20" onclick="removePackage(${i})">Pakket verwijderen</button></div><div style="margin:8px 0">${p.items.map((x,j)=>`<span style="display:inline-block;background:#f0f4f9;border-radius:6px;padding:5px 7px;margin:3px">${esc(x.code)} · ${esc(x.status)} ×${x.qty||1} <b style="cursor:pointer;color:#d92d20" onclick="removePackItem(${i},${j})">×</b></span>`).join('')}</div><div style="display:grid;grid-template-columns:1fr 120px 80px auto;gap:6px"><select class="mini" id="pic${i}">${items.map((x,k)=>`<option value="${k}">${esc(x.code)} — ${esc(x.description)}</option>`).join('')}</select><select class="mini" id="pis${i}"><option>Nieuw</option><option>Refurb</option></select><input class="mini" type="number" min="1" value="1" id="piq${i}"><button class="smallbtn" onclick="addPackItem(${i})">+ Artikel</button></div></div>`).join('')}`}}
function newArticle(){let code=acode.value.trim(),description=adesc.value.trim(),status=astatus.value,category=acat.value.trim()||'Overig';if(!code)return toast('Artikelnummer ontbreekt');items.push({code,description,status,category});save();fillCats();renderArticles();renderAdmin();toast('Artikel toegevoegd')}
function removeArticle(i){if(!confirm('Artikel verwijderen?'))return;items.splice(i,1);save();fillCats();renderArticles();renderAdmin()}
function newPackage(){let name=pname.value.trim();if(!name)return;packages.push({name,items:[]});save();renderPacks();renderAdmin()} function removePackage(i){if(!confirm('Pakket verwijderen?'))return;packages.splice(i,1);save();renderPacks();renderAdmin()} function removePackItem(i,j){packages[i].items.splice(j,1);save();renderAdmin()}
function addPackItem(i){let x=items[+document.getElementById('pic'+i).value],status=document.getElementById('pis'+i).value,qty=Math.max(1,+document.getElementById('piq'+i).value||1);packages[i].items.push({code:x.code,status,qty});save();renderAdmin()}
function resetData(){if(!confirm('Alle lokale wijzigingen terugzetten naar de Excel-startdata?'))return;items=clone(BASE_ITEMS);packages=clone(BASE_PACKAGES);save();fillCats();renderPacks();renderArticles();renderAdmin();toast('Startdata hersteld')}
init();