from pathlib import Path

root=Path(__file__).resolve().parents[1]
maker=root/'web/components/aster-strategy2-maker.tsx'
markets=root/'web/components/markets-page.tsx'

maker.write_text(r'''"use client";

import { useEffect, useMemo, useState } from "react";
import { authenticatedRequest } from "@/lib/cloud-client";
import { strategy2ServerStatus } from "@/lib/aster-strategy2-server-status.mjs";

type Side="LONG"|"SHORT";
type Profile={entryMarginUsd:string;minimumLeverage:string;dcaDistance:string;dcaMarginUsd:string;maxDca:string;unlimitedDca:boolean;takeProfit:string;autoRestart:boolean};
type Core={name:string;universeTopN:string;maximumPositions:string;longSlots:string;shortSlots:string;mode:"paper"|"live"};
const profileDefault:Profile={entryMarginUsd:"5",minimumLeverage:"50",dcaDistance:"0.30",dcaMarginUsd:"2",maxDca:"3",unlimitedDca:false,takeProfit:"1.50",autoRestart:true};
const coreDefault:Core={name:"Aster Multi DCA",universeTopN:"30",maximumPositions:"30",longSlots:"20",shortSlots:"10",mode:"live"};
const num=(v:string)=>Number(v)||0;
const pct=(v:unknown,fallback:number)=>String(Number(v??fallback)*100);
const profileFrom=(raw:unknown,base:Record<string,unknown>):Profile=>{const p=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};return{
 entryMarginUsd:String(p.entryMarginUsd??base.entryMarginUsd??5),minimumLeverage:String(p.minimumLeverage??base.minimumLeverage??50),
 dcaDistance:pct(p.dcaDistance,Number(base.dcaDistance??.003)),dcaMarginUsd:String(p.dcaMarginUsd??base.dcaMarginUsd??2),
 maxDca:String(p.maxDca??base.maxDca??3),unlimitedDca:Boolean(p.unlimitedDca??base.unlimitedDca??false),takeProfit:pct(p.takeProfit,Number(base.takeProfit??.015)),autoRestart:Boolean(p.autoRestart??true)};};
const toProfile=(p:Profile)=>({entryMarginUsd:num(p.entryMarginUsd),entrySizingMode:"margin",minimumLeverage:Math.max(1,Math.round(num(p.minimumLeverage))),dcaDistance:num(p.dcaDistance)/100,dcaMarginUsd:num(p.dcaMarginUsd),maxDca:Math.max(0,Math.round(num(p.maxDca))),unlimitedDca:p.unlimitedDca,takeProfit:num(p.takeProfit)/100,autoRestart:p.autoRestart});

function Field({label,value,onChange,suffix}:{label:string;value:string;onChange:(x:string)=>void;suffix?:string}){return <label style={{display:"grid",gap:5,fontSize:12,fontWeight:700}}><span style={{opacity:.78}}>{label}</span><span style={{display:"flex",alignItems:"center",gap:7}}><input value={value} onChange={e=>onChange(e.target.value.replace(",","."))} inputMode="decimal" style={{width:"100%"}}/>{suffix&&<small>{suffix}</small>}</span></label>}
function Toggle({label,checked,onChange,help}:{label:string;checked:boolean;onChange:(v:boolean)=>void;help?:string}){return <label className="manual-symbol-toggle"><span><b>{label}</b>{help&&<small>{help}</small>}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
function ProfilePanel({side,value,set}:{side:Side;value:Profile;set:(p:Profile)=>void}){const patch=(k:keyof Profile,v:string|boolean)=>set({...value,[k]:v});return <details open className="strategy-message" style={{padding:14}}><summary style={{cursor:"pointer",fontWeight:900}}>STANDARD {side}</summary><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10,marginTop:12}}><Field label="Start margin" value={value.entryMarginUsd} onChange={v=>patch("entryMarginUsd",v)} suffix="USDT"/><Field label="Minimum leverage" value={value.minimumLeverage} onChange={v=>patch("minimumLeverage",v)} suffix="×"/><Field label="DCA afstand" value={value.dcaDistance} onChange={v=>patch("dcaDistance",v)} suffix="%"/><Field label="DCA margin" value={value.dcaMarginUsd} onChange={v=>patch("dcaMarginUsd",v)} suffix="USDT"/><Field label="Max DCA" value={value.maxDca} onChange={v=>patch("maxDca",v)}/><Field label="Take Profit" value={value.takeProfit} onChange={v=>patch("takeProfit",v)} suffix="%"/></div><div style={{marginTop:10,display:"grid",gap:8}}><Toggle label="Onbeperkt DCA" checked={value.unlimitedDca} onChange={v=>patch("unlimitedDca",v)} help="Normale margin-, leverage- en exchangechecks blijven actief."/><Toggle label="Auto-herstart na TP" checked={value.autoRestart} onChange={v=>patch("autoRestart",v)}/></div></details>}

export function AsterStrategy2Maker({snapshot,serverConfirmed,onConfirmed,onChanged}:{snapshot:Record<string,unknown>|null;serverConfirmed:boolean;onConfirmed:(x:Record<string,unknown>)=>void;onChanged:()=>void}){
 const [core,setCore]=useState(coreDefault),[long,setLong]=useState(profileDefault),[short,setShort]=useState(profileDefault),[pairSymbol,setPairSymbol]=useState(""),[pairMaxDca,setPairMaxDca]=useState(""),[pairOverrides,setPairOverrides]=useState<Record<string,Record<string,unknown>>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[dirty,setDirty]=useState(false),[confirmedState,setConfirmedState]=useState<Record<string,unknown>|null>(null);
 const snapshotState=(snapshot?.strategy2&&typeof snapshot.strategy2==="object"?snapshot.strategy2:{}) as Record<string,unknown>;const status=strategy2ServerStatus(snapshotState,confirmedState,serverConfirmed);const state=status.state as Record<string,unknown>;
 useEffect(()=>{const x=state.settings as Record<string,unknown>|undefined;if(!x||String(x.engine||x.strategyKind)!=="multi_bb_v1"||dirty)return;setCore({name:String(x.name||coreDefault.name),universeTopN:String(x.universeTopN??30),maximumPositions:String(x.maximumPositions??30),longSlots:String(x.longSlots??20),shortSlots:String(x.shortSlots??10),mode:x.mode==="paper"?"paper":"live"});setLong(profileFrom(x.standardLong,x));setShort(profileFrom(x.standardShort,x));setPairOverrides(x.pairOverrides&&typeof x.pairOverrides==="object"?x.pairOverrides as Record<string,Record<string,unknown>>:{});},[state.settings,dirty]);
 const settings=useMemo(()=>({engine:"multi_bb_v1",strategyKind:"multi_bb_v1",name:core.name,mode:core.mode,universeTopN:Math.round(num(core.universeTopN)),maximumPositions:Math.round(num(core.maximumPositions)),longSlots:Math.round(num(core.longSlots)),shortSlots:Math.round(num(core.shortSlots)),minimumLeverage:Math.round(num(long.minimumLeverage)),entryMarginUsd:num(long.entryMarginUsd),entryNotionalUsd:num(long.entryMarginUsd)*Math.max(1,Math.round(num(long.minimumLeverage))),entrySizingMode:"margin",dcaDistance:num(long.dcaDistance)/100,dcaMarginUsd:num(long.dcaMarginUsd),maxDca:Math.round(num(long.maxDca)),unlimitedDca:long.unlimitedDca,takeProfit:num(long.takeProfit)/100,entryMode:"immediate_fill",marginMode:"cross",autoRestart:true,manualSymbolSelectionEnabled:false,manualSymbols:[],standardLong:toProfile(long),standardShort:toProfile(short),pairOverrides}),[core,long,short,pairOverrides]);
 const changed=<T,>(setter:(v:T)=>void)=>(v:T)=>{setter(v);setDirty(true)};
 async function save(){setBusy(true);setMessage("");try{const result=await authenticatedRequest("/api/exchanges/aster/strategy2/settings",{method:"PUT",body:JSON.stringify({settings})}) as Record<string,unknown>;const s=result.strategy2&&typeof result.strategy2==="object"?result.strategy2 as Record<string,unknown>:null;if(s){setConfirmedState(s);onConfirmed(s)}setDirty(false);setMessage("Instellingen server-side opgeslagen. Actieve trades zijn niet gereset of gesloten.");await Promise.resolve(onChanged());}catch(e){setMessage(e instanceof Error?e.message:"Opslaan mislukt")}finally{setBusy(false)}}
 async function simulate(){setBusy(true);setMessage("");try{await authenticatedRequest("/api/exchanges/aster/strategy2/simulate",{method:"POST",body:JSON.stringify({settings})});setMessage("Configuratie geldig · 0 orders verzonden.");}catch(e){setMessage(e instanceof Error?e.message:"Validatie mislukt")}finally{setBusy(false)}}
 async function toggle(){setBusy(true);setMessage("");try{const route=status.enabled?"stop":"start";const body=status.enabled?{confirm:true}:{confirm:true,settings};const result=await authenticatedRequest(`/api/exchanges/aster/strategy2/${route}`,{method:"POST",body:JSON.stringify(body)}) as Record<string,unknown>;const s=result.strategy2&&typeof result.strategy2==="object"?result.strategy2 as Record<string,unknown>:null;if(s){setConfirmedState(s);onConfirmed(s)}setMessage(status.enabled?"Bot gestopt. Open posities blijven exchange-truth.":"Botstart server-side bevestigd.");await Promise.resolve(onChanged());}catch(e){setMessage(e instanceof Error?e.message:"Actie mislukt")}finally{setBusy(false)}}
 function saveOverride(){const symbol=pairSymbol.trim().toUpperCase();if(!symbol.endsWith("USDT")||!pairMaxDca.trim()){setMessage("Vul een geldige USDT-pair en Max DCA in.");return}changed(setPairOverrides)({...pairOverrides,[symbol]:{...(pairOverrides[symbol]||{}),maxDca:Math.max(0,Math.round(num(pairMaxDca)))}});setPairSymbol(symbol);setMessage(`${symbol}: CUSTOM Max DCA voorbereid. Klik Opslaan om persistent te maken.`)}
 function resetOverride(){const symbol=pairSymbol.trim().toUpperCase();if(!symbol)return;const next={...pairOverrides};delete next[symbol];changed(setPairOverrides)(next);setPairMaxDca("");setMessage(`${symbol}: teruggezet naar STANDARD profiel. Klik Opslaan.`)}
 return <article id="strategy-2-maker" className="strategy-card strategy-two-card"><div className="strategy-title-row"><div><span className="kicker">ASTER BOT</span><h2>Strategy 2 instellingen</h2></div><span className={`strategy-state ${status.enabled?"on":""}`}>{status.enabled?"AAN":"UIT"}</span></div><p>Direct instellingenpaneel zonder wizard. Hiërarchie: globale basis → STANDARD LONG/SHORT → pair override.</p>
 <div className={`strategy-power-control ${status.enabled?"enabled":"ready"}`}><span><b>Strategy 2 live bot</b><small>{status.enabled?"draait":"uit"}</small></span><button type="button" role="switch" aria-checked={status.enabled===true} disabled={busy||status.pending} onClick={toggle}><i/>{status.enabled?"Uitschakelen":"Inschakelen"}</button></div>
 <details open className="strategy-message" style={{padding:14}}><summary style={{cursor:"pointer",fontWeight:900}}>Globale capaciteit</summary><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10,marginTop:12}}><Field label="Top-N volume" value={core.universeTopN} onChange={v=>changed(setCore)({...core,universeTopN:v})}/><Field label="Totaal posities" value={core.maximumPositions} onChange={v=>changed(setCore)({...core,maximumPositions:v})}/><Field label="LONG slots" value={core.longSlots} onChange={v=>changed(setCore)({...core,longSlots:v})}/><Field label="SHORT slots" value={core.shortSlots} onChange={v=>changed(setCore)({...core,shortSlots:v})}/></div></details>
 <ProfilePanel side="LONG" value={long} set={changed(setLong)}/><ProfilePanel side="SHORT" value={short} set={changed(setShort)}/>
 <details className="strategy-message" style={{padding:14}}><summary style={{cursor:"pointer",fontWeight:900}}>Pair override</summary><p>Voor actieve trades zijn runtime-veilige wijzigingen zoals Max DCA direct bruikbaar zonder state-reset. Bestaande fills en DCA-teller blijven behouden.</p><div style={{display:"grid",gridTemplateColumns:"1.4fr 1fr",gap:10}}><Field label="Pair" value={pairSymbol} onChange={v=>setPairSymbol(v.toUpperCase())}/><Field label="CUSTOM Max DCA" value={pairMaxDca} onChange={setPairMaxDca}/></div><div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}><button type="button" className="expand-settings" onClick={saveOverride}>CUSTOM toepassen</button><button type="button" className="expand-settings" onClick={resetOverride}>Reset naar standaard</button></div>{pairSymbol.trim().toUpperCase()&&pairOverrides[pairSymbol.trim().toUpperCase()]&&<p><b>CUSTOM</b> · {JSON.stringify(pairOverrides[pairSymbol.trim().toUpperCase()])}</p>}</details>
 <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><button className="expand-settings" disabled={busy||!dirty} onClick={save}>{busy?"Bezig…":dirty?"Opslaan":"Opgeslagen"}</button><button className="expand-settings" disabled={busy} onClick={simulate}>Test configuratie</button></div>{dirty&&<p className="strategy-message"><b>Niet-opgeslagen wijzigingen.</b> Actieve cycles worden niet stilzwijgend gereset.</p>}{message&&<p className="strategy-message">{message}</p>}</article>;
}
''',encoding='utf-8')

text=markets.read_text(encoding='utf-8')
if 'SafeTradingChart' not in text:
    text=text.replace('import { authenticatedRequest } from "@/lib/cloud-client";','import { authenticatedRequest } from "@/lib/cloud-client";\nimport { SafeTradingChart } from "@/components/trading-chart";')
if 'const [chartRow' not in text:
    text=text.replace('  const [quickMessage, setQuickMessage] = useState("");','  const [quickMessage, setQuickMessage] = useState("");\n  const [chartRow, setChartRow] = useState<MarketRow | null>(null);')
# Add chart button next to quick trade actions created by phase2.
needle='<button type="button" className={styles.quickLong} disabled={quickBusy} onClick={() => void prepareQuickTrade(row, "LONG")}>Buy Long</button><button type="button" className={styles.quickShort} disabled={quickBusy} onClick={() => void prepareQuickTrade(row, "SHORT")}>Buy Short</button>'
if needle in text and 'Open chart' not in text:
    text=text.replace(needle,'<button type="button" className={styles.quickLong} disabled={quickBusy} onClick={() => void prepareQuickTrade(row, "LONG")}>Buy Long</button><button type="button" className={styles.quickShort} disabled={quickBusy} onClick={() => void prepareQuickTrade(row, "SHORT")}>Buy Short</button><button type="button" className={styles.chartButton} onClick={() => setChartRow(row)}>Open chart</button>')
# Fallback: inject chart trigger before article close for phase2 structure.
if 'Open chart' not in text:
    text=text.replace('</article>)}</div>}','<button type="button" className={styles.chartButton} onClick={() => setChartRow(row)}>Open chart</button></article>)}</div>}')
# Shared chart overlay before final section close.
anchor='    {error && data && <div className={styles.staleWarning}>{error}</div>}\n  </section>;'
chart='''    {error && data && <div className={styles.staleWarning}>{error}</div>}\n    {chartRow && <div className={styles.chartOverlay} role="dialog" aria-modal="true" aria-label={`${chartRow.symbol} chart`}><div className={styles.chartSheet}><div className={styles.chartHeader}><div><b>{chartRow.symbol}</b><small>Dezelfde Aster chart-engine als Trade Center</small></div><button type="button" onClick={() => setChartRow(null)}>Terug naar Markets</button></div><SafeTradingChart mode="aster-detail" selection={{id:`markets:${chartRow.symbol}`,symbol:chartRow.symbol,exchange:"aster",side:""}} /></div></div>}\n  </section>;'''
if anchor in text and 'chartOverlay' not in text:
    text=text.replace(anchor,chart)
markets.write_text(text,encoding='utf-8')

css=root/'web/components/markets-page.module.css'
c=css.read_text(encoding='utf-8')
if '.chartOverlay' not in c:
    c+='''\n.chartButton{border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.04);color:inherit;border-radius:10px;padding:8px 10px;font-weight:800}.chartOverlay{position:fixed;inset:0;z-index:1400;background:#07090d;overflow:auto;padding:12px}.chartSheet{max-width:1200px;margin:0 auto}.chartHeader{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 2px 14px}.chartHeader>div{display:grid;gap:2px}.chartHeader small{opacity:.65}.chartHeader button{border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.06);color:inherit;border-radius:10px;padding:9px 12px;font-weight:800}@media(max-width:700px){.chartOverlay{padding:8px}.chartHeader{position:sticky;top:0;background:#07090d;z-index:2}}\n'''
    css.write_text(c,encoding='utf-8')
print('phase3 applied')
