from pathlib import Path

path = Path('web/components/trading-chart.tsx')
src = path.read_text(encoding='utf-8')

old = '''  const focusTakeProfitPrice=useMemo(()=>{\n    const explicit=Number(cockpit?.longTakeProfitPrice||0);if(Number.isFinite(explicit)&&explicit>0)return explicit;\n    const entry=Number(cockpit?.longEntry||0),qty=Math.abs(Number(cockpit?.longQuantity||0)),value=Number(cockpit?.tpValue||0),mode=String(cockpit?.tpMode||\"\").toLowerCase();\n    if(!(entry>0&&value>0))return 0;\n    if(mode===\"usdt\"&&qty>0)return entry+(value/qty);\n    if(mode===\"percent\"&&value>0&&value<1)return entry/(1-value);\n    return 0;\n  },[cockpit]);\n'''
assert old in src, 'legacy position-TP calculation block not found'
src = src.replace(old, '  const focusTakeProfitPrice=0; // v7 has no position-level TP; portfolio equity target is the only cycle exit.\n')

old = '''      if(focusV2){const step=timeframeSeconds[timeframe]||60;const end=(next.time+step*18) as UTCTimestamp;const setSegment=(key:string,price:unknown,visible=true)=>{const series=focusSegmentRefs.current[key];const n=Number(price);if(!series)return;if(!visible||!Number.isFinite(n)||n<=0){series.setData([]);return}series.setData([{time:next.time as UTCTimestamp,value:n},{time:end,value:n}])};const v5=Number(cockpit?.stateMachineVersion||0)>=5;const hedgeActive=v5&&Number(cockpit?.shortQuantity||0)>0&&String(cockpit?.hedgeState||\"\").toUpperCase()!==\"OFF\";setSegment(\"live\",next.close);setSegment(\"be\",cockpit?.longBreakEvenPrice);setSegment(\"dca\",cockpit?.nextLongDcaPrice);setSegment(\"tp\",focusTakeProfitPrice);setSegment(\"release\",cockpit?.hedgeReleasePrice||cockpit?.nextShortReleasePrice,hedgeActive);}\n'''
new = '''      if(focusV2){const step=timeframeSeconds[timeframe]||60;const end=(next.time+step*18) as UTCTimestamp;const setSegment=(key:string,price:unknown,visible=true)=>{const series=focusSegmentRefs.current[key];const n=Number(price);if(!series)return;if(!visible||!Number.isFinite(n)||n<=0){series.setData([]);return}series.setData([{time:next.time as UTCTimestamp,value:n},{time:end,value:n}])};const hedgeActive=Number(cockpit?.shortQuantity||0)>0&&String(cockpit?.hedgeState||\"\").toUpperCase()!==\"OFF\";const rawNextBuy=Number(cockpit?.nextLongDcaPrice||0);const safeNextBuy=rawNextBuy>0&&rawNextBuy<next.close?rawNextBuy:0;setSegment(\"live\",next.close);setSegment(\"be\",0);setSegment(\"dca\",safeNextBuy);setSegment(\"tp\",0);setSegment(\"release\",cockpit?.hedgeReleasePrice||cockpit?.nextShortReleasePrice,hedgeActive);}\n'''
assert old in src, 'legacy realtime focus segment block not found'
src = src.replace(old, new)

start = src.index('  const focusTpLabel=useMemo(')
end = src.index('  syncFocusLevelsRef.current=', start)
replacement = '''  const focusRawNextBuy=Number(cockpit?.nextLongDcaPrice||0);\n  const focusNextBuyInvariantOk=focusLivePrice>0&&focusRawNextBuy>0&&focusRawNextBuy<focusLivePrice;\n  const focusNextBuyDistancePct=focusNextBuyInvariantOk?Math.max(0,((focusLivePrice-focusRawNextBuy)/focusLivePrice)*100):null;\n  const focusInvariantViolation=focusRawNextBuy>0&&!focusNextBuyInvariantOk;\n  const focusPortfolioTargetLabel=useMemo(()=>{const mode=String(cockpit?.tpMode||\"\").toLowerCase(),value=Number(cockpit?.tpValue||0);if(!(value>0))return\"PORTFOLIO DOEL\";return mode===\"percent\"?`PORTFOLIO DOEL +${(value*100).toFixed(2)}%`:`PORTFOLIO DOEL +$${value.toFixed(2)}`},[cockpit]);\n  const distanceLabel=(price:number)=>focusLivePrice>0&&price>0?`${((price/focusLivePrice)-1)*100>=0?\"+\":\"\"}${(((price/focusLivePrice)-1)*100).toFixed(2)}%`:\"—\";\n  const focusLevels=useMemo(()=>{if(!focusV2||!cockpit)return[] as Array<{key:string;price:number;label:string;color:string}>;const rows=[{key:\"live\",price:focusLivePrice,label:\"LIVE\",color:\"#25df91\"}];if(focusNextBuyInvariantOk)rows.push({key:\"dca\",price:focusRawNextBuy,label:`TRAILING TERUGVALKOOP ${focusNextBuyDistancePct===null?\"—\":`-${focusNextBuyDistancePct.toFixed(2)}%`}`,color:\"#ffd166\"});const lastFill=Number(cockpit?.lastDcaFillPrice||0);if(lastFill>0)rows.push({key:\"lastfill\",price:lastFill,label:`LAATST GEVULDE KOOP ${distanceLabel(lastFill)}`,color:\"#4aa3ff\"});if(focusHedgeActive&&focusReleasePrice>0)rows.push({key:\"release\",price:focusReleasePrice,label:`SHORT RELEASE ${distanceLabel(focusReleasePrice)}`,color:\"#ff9f43\"});const rehedge=Number(cockpit?.rehedgePrice||0);if(Boolean(cockpit?.rehedgeArmed)&&rehedge>0)rows.push({key:\"rehedge\",price:rehedge,label:`RE-HEDGE ${distanceLabel(rehedge)}`,color:\"#f06292\"});return rows.filter(row=>Number.isFinite(row.price)&&row.price>0)},[focusV2,cockpit,focusLivePrice,focusNextBuyInvariantOk,focusRawNextBuy,focusNextBuyDistancePct,focusHedgeActive,focusReleasePrice]);\n'''
src = src[:start] + replacement + src[end:]

old = '''{focusV2&&cockpit&&<div className=\"focus-cockpit-levels\"><span className=\"current\">LIVE {focusLivePrice>0?focusLivePrice.toLocaleString(\"nl-NL\",{maximumFractionDigits:8}):\"—\"}</span>{Number(cockpit.longBreakEvenPrice)>0&&<span className=\"breakeven\">BE {Number(cockpit.longBreakEvenPrice).toLocaleString(\"nl-NL\",{maximumFractionDigits:8})}</span>}{Number(cockpit.nextLongDcaPrice)>0&&<span className=\"dca\">{focusHedgeActive?\"DCA / SHORT SYNC\":\"DCA / FULL SHORT RE-HEDGE\"} {Number(cockpit.nextLongDcaPrice).toLocaleString(\"nl-NL\",{maximumFractionDigits:8})}</span>}{focusTakeProfitPrice>0&&<span className=\"tp\">TP {focusTakeProfitPrice.toLocaleString(\"nl-NL\",{maximumFractionDigits:8})}</span>}{focusHedgeActive&&focusReleasePrice>0&&<span className=\"release\">SHORT RELEASE {Boolean(cockpit.shortReleasePriceReady)?(Boolean(cockpit.shortReleaseNetGreenReady)?\"READY · NET GREEN\":\"PRICE READY · WAIT NET GREEN\"):\"+0.15%\"} {focusReleasePrice.toLocaleString(\"nl-NL\",{maximumFractionDigits:8})}</span>}</div>}'''
new = '''{focusV2&&cockpit&&<div className=\"focus-cockpit-levels\"><span className=\"current\">LIVE {focusLivePrice>0?focusLivePrice.toLocaleString(\"nl-NL\",{maximumFractionDigits:8}):\"—\"}</span>{focusNextBuyInvariantOk&&<span className=\"dca\">TRAILING TERUGVALKOOP {focusRawNextBuy.toLocaleString(\"nl-NL\",{maximumFractionDigits:8})} · nog {focusNextBuyDistancePct?.toFixed(2)}% daling</span>}{focusInvariantViolation&&<span className=\"dca\">STRATEGY INVARIANT VIOLATION · terugvalkoop verborgen omdat niveau niet onder LIVE ligt</span>}{Number(cockpit.lastDcaFillPrice)>0&&<span className=\"breakeven\">LAATST GEVULDE KOOP {Number(cockpit.lastDcaFillPrice).toLocaleString(\"nl-NL\",{maximumFractionDigits:8})}</span>}{focusHedgeActive&&focusReleasePrice>0&&<span className=\"release\">SHORT RELEASE {focusReleasePrice.toLocaleString(\"nl-NL\",{maximumFractionDigits:8})}</span>}{Boolean(cockpit.rehedgeArmed)&&Number(cockpit.rehedgePrice)>0&&<span className=\"release\">RE-HEDGE {Number(cockpit.rehedgePrice).toLocaleString(\"nl-NL\",{maximumFractionDigits:8})}</span>}<span className=\"tp\">{focusPortfolioTargetLabel}</span></div>}'''
assert old in src, 'legacy cockpit level strip not found'
src = src.replace(old, new)

for forbidden in ('PRICE READY · WAIT NET GREEN', 'READY · NET GREEN'):
    assert forbidden not in src, f'legacy gate still present: {forbidden}'

path.write_text(src, encoding='utf-8')
print('patched', path)
