from pathlib import Path
p=Path(__file__).with_name('focus_v2_builder.py')
s=p.read_text()
s=s.replace('anchor="    focus_airbag_drawdown_3: float = 0.05\\n"','anchor="    focus_airbag_drawdown_3: float = .05\\n"')
s=s.replace('parse_anchor=\'            focus_airbag_drawdown_3=float(raw.get("focusAirbagDrawdown3",0.05)),\\n\'','parse_anchor=\'            focus_airbag_drawdown_3=f("focusAirbagDrawdown3", .05),\\n\'')
s=s.replace('focus_v2_enabled=bool(raw.get("focusV2Enabled",False)),\\n            focus_v2_min_net_long_usdt=float(raw.get("focusV2MinNetLongUsdt",5.0)),\\n            focus_v2_min_net_long_ratio=float(raw.get("focusV2MinNetLongRatio",0.02)),\\n            focus_v2_max_hedge_ratio=float(raw.get("focusV2MaxHedgeRatio",0.95)),\\n            focus_v2_release_ratio=float(raw.get("focusV2ReleaseRatio",0.33)),\\n            focus_v2_recovery_rebound_pct=float(raw.get("focusV2RecoveryReboundPct",0.003)),\\n            focus_v2_portfolio_recovery_ratio=float(raw.get("focusV2PortfolioRecoveryRatio",0.99)),\\n            focus_v2_rehedge_setback_pct=float(raw.get("focusV2RehedgeSetbackPct",0.003)),','focus_v2_enabled=bool(raw.get("focusV2Enabled",False)),\\n            focus_v2_min_net_long_usdt=f("focusV2MinNetLongUsdt",5.0),\\n            focus_v2_min_net_long_ratio=f("focusV2MinNetLongRatio",0.02),\\n            focus_v2_max_hedge_ratio=f("focusV2MaxHedgeRatio",0.95),\\n            focus_v2_release_ratio=f("focusV2ReleaseRatio",0.33),\\n            focus_v2_recovery_rebound_pct=f("focusV2RecoveryReboundPct",0.003),\\n            focus_v2_portfolio_recovery_ratio=f("focusV2PortfolioRecoveryRatio",0.99),\\n            focus_v2_rehedge_setback_pct=f("focusV2RehedgeSetbackPct",0.003),')
old='''    # Strategy2Settings parser uses `return config`; only insert into from_dict block once.\n    marker="        return config\\n"\n    if marker not in text: raise SystemExit("Strategy2Config return anchor missing")\n    text=text.replace(marker,validation+marker,1)\n    (ROOT/settings_path).write_text(text)\n'''
new='''    marker="        return self\\n"\n    validation=validation.replace("config.","self.")\n    if marker not in text: raise SystemExit("Strategy2Config validated return anchor missing")\n    text=text.replace(marker,validation+marker,1)\n    public_anchor='''            "focusAirbagDrawdown1":self.focus_airbag_drawdown_1,"focusAirbagDrawdown2":self.focus_airbag_drawdown_2,"focusAirbagDrawdown3":self.focus_airbag_drawdown_3,\\n'''\n    public_add='''            "focusV2Enabled":self.focus_v2_enabled,"focusV2MinNetLongUsdt":self.focus_v2_min_net_long_usdt,"focusV2MinNetLongRatio":self.focus_v2_min_net_long_ratio,\\n            "focusV2MaxHedgeRatio":self.focus_v2_max_hedge_ratio,"focusV2ReleaseRatio":self.focus_v2_release_ratio,"focusV2RecoveryReboundPct":self.focus_v2_recovery_rebound_pct,\\n            "focusV2PortfolioRecoveryRatio":self.focus_v2_portfolio_recovery_ratio,"focusV2RehedgeSetbackPct":self.focus_v2_rehedge_setback_pct,"focusV2RequireBollingerMiddle":self.focus_v2_require_bollinger_middle,\\n'''\n    if public_anchor not in text: raise SystemExit("Strategy2Config public_dict anchor missing")\n    text=text.replace(public_anchor,public_anchor+public_add,1)\n    (ROOT/settings_path).write_text(text)\n'''
if old not in s: raise SystemExit('validation patch anchor missing in builder')
s=s.replace(old,new,1)
p.write_text(s)
print('builder aligned')
